//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da testConn.rc
//
#define IDB_BITMAP_CFG                  1
#define IDI_ICON1                       1
#define IDD_CLIENT                      1
#define IDD_PROGRESS                    2
#define IDC_RTS_FORCE                   2
#define IDD_DIALOG_NUMBER               3
#define IDB_BITMAP_SEND                 3
#define IDOK3                           3
#define IDC_DTR_FORCE                   3
#define IDB_BITMAP_DONE                 4
#define IDD_PARAM                       5
#define IDB_BITMAP_DEF                  6
#define IDB_BITMAP_CANC                 7
#define IDB_BITMAP_OK                   8
#define IDB_BITMAP_SAVE                 9
#define IDB_BITMAP_CLEAR                10
#define IDB_BITMAP_GREEN_SEM            11
#define IDB_BITMAP_RED_SEM              12
#define IDC_STATICTEXT_INFO_NUM         101
#define IDC_GROUPBOX1                   101
#define IDC_STATICTEXT_BAUDRATE         101
#define IDC_PROGRESSBAR_COMM            101
#define IDD_DIALOG_STAT                 101
#define IDC_EDIT_NUMBER                 102
#define IDC_GROUPBOX2                   102
#define IDC_STATICTEXT_DATALEN          102
#define IDC_STATICTEXT_PROGRESS         102
#define IDC_BUTTON_SEND_FILE            103
#define IDC_STATICTEXT_PARITY           103
#define IDC_BUTTON_ABORT_COMM           103
#define IDC_STATICTEXT_2                104
#define IDC_STATICTEXT_BITSTOP          104
#define IDC_STATICTEXT_3                105
#define IDC_COMBOBOX_BAUDRATE           105
#define IDC_STATICTEXT_4                106
#define IDC_COMBOBOX_DATA_LEN           106
#define IDC_EDIT_STRING                 107
#define IDC_COMBOBOX_PARITY             107
#define IDC_EDIT_DEC                    108
#define IDC_COMBOBOX_BITSTOP            108
#define IDC_EDIT_HEX                    109
#define IDC_BUTTON_DEFAULT              109
#define IDC_EDIT_BIN                    110
#define IDC_STATICFRAME_PARAM           110
#define IDC_BUTTONOPEN_COM              111
#define IDC_STATICTEXT_COM_PORT         111
#define IDC_BUTTON_SEND_STRING          112
#define IDC_COMBOBOX_COM_PORT           112
#define IDC_BUTTON_SEND_BYTE            113
#define IDC_STATICTEXT3                 113
#define IDC_BUTTON_SETUP                114
#define IDC_EDIT_MS_DELAY               114
#define IDC_EDIT_REC                    115
#define IDC_CHECKBOX_MODEM              115
#define IDC_STATICTEXT_REC              116
#define IDC_RADIOBUTTON_TONE            116
#define IDC_BUTTON_CLEAR                117
#define IDC_RADIOBUTTON_PULSE           117
#define IDC_BUTTON_SAVE                 118
#define IDC_CHECKBOX_LAN                118
#define IDC_EDIT_CHAR                   119
#define IDC_STATICFRAME2                119
#define IDC_CHECKBOX_SHOW_HEX           120
#define IDC_STATICFRAME3                120
#define IDC_CHECKBOX_CAPTURE_TO_FILE    121
#define IDC_RADIOBUTTON_SERVER          121
#define IDC_STATICFRAME1                122
#define IDC_RADIOBUTTON_CLIENT          122
#define IDC_STATICTEXT2                 123
#define IDC_STATICFRAME4                123
#define IDC_EDIT_INIT_MODEM             124
#define IDC_CHECKBOX_SHOW_COM           124
#define IDC_STATICTEXT4                 125
#define IDC_CHECKBOX_CAPTURE_TO_FILE2   125
#define IDC_CHECKBOX_NO_MSGBOX          125
#define IDC_RADIOBUTTON_TCP             126
#define IDC_RADIOBUTTON_UDP             127
#define IDC_STATICTEXT_BITSTOP2         128
#define IDC_COMBOBOX_DTR_DSR            129
#define IDC_STATICTEXT_BITSTOP3         130
#define IDC_COMBOBOX_RTS_CTS            131
#define IDC_STATICTEXT_BITSTOP4         132
#define IDC_COMBOBOX_XON_XOFF           133
#define IDC_CHECKBOX_485                134
#define IDC_STATICTEXT5                 135
#define IDC_EDIT_MS_DELAY2              136
#define IDC_EDIT_DIM_PACKET             136
#define IDC_STATIC_CTS_ON               201
#define IDC_STATIC_DSR_ON               202
#define IDC_STATIC_RING_ON              203
#define IDC_STATIC_RLSD_ON              204
#define IDC_STATIC_CTS_W                205
#define IDC_STATIC_DSR_W                206
#define IDC_STATIC_RLSD_W               207
#define IDC_STATIC_XOFF_R               208
#define IDC_STATIC_XOFF_T               209
#define IDC_STATIC_Q_IN                 210
#define IDC_STATIC_Q_OUT                211
#define IDC_RADIO_RTS_ON                212
#define IDC_RADIO_RTS_OFF               213
#define IDC_RADIO_DTR_ON                214
#define IDC_RADIO_DTR_OFF               215
#define IDC_CHECK_AUTO_REFRESH          216
#define IDC_EDIT1                       217
#define IDC_EDIT_AUTO_REFRESH           217
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         218
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
