.PHONY: clean All

All:
	@echo "----------Building project:[ wrap - Release ]----------"
	@cd "wrap" && "$(MAKE)" -f  "wrap.mk"
clean:
	@echo "----------Cleaning project:[ wrap - Release ]----------"
	@cd "wrap" && "$(MAKE)" -f  "wrap.mk" clean
