//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_ICON_NPS                    1
#define IDB_OK                          1
#define IDR_241                         1
#define IDB_CANC                        2
#define IDC_MYICON                      2
#define IDI_ICON_TIMER                  2
#define IDD_CHOOSE_INFO_TREE            2
#define IDD_CHOOSE_PRINT                3
#define IDC_CURS_HAND                   4
#define IDD_BASE_MODAL_NO_CAPTION       4
#define IDD_LGRAPH_SHOWVALUE            5
#define IDC_CURS_SLIDER_DX              5
#define IDC_CURS_SLIDER_SX              6
#define IDD_PSW_1000                    6
#define IDD_PSW_SHOW                    7
#define IDI_ICON_SYSTRAY_1              7
#define IDI_ICON_SYSTRAY_2              8
#define IDD_CHOOSE_PAGE                 8
#define IDI_ICON_SYSTRAY_3              9
#define IDD_CHOOSE_PAGE_TREEVIEW        9
#define IDD_CHOOSE_PAGE_LISTVIEW        10
#define IDI_OPER                        10
#define IDI_LOGS                        11
#define IDD_CHOOSE_LIST_CAUSE           11
#define IDI_DATE                        12
#define IDI_ARROW                       13
#define IDI_ARROW_DN                    14
#define IDC_CURSOR_PAN                  15
#define IDC_CURSOR_PAN_MOVE             16
#define IDD_SAVE_DATA                   17
#define IDD_FILTER_REPORT               18
#define IDD_INFO                        25
#define IDD_CHOOSE_DATE_EXPORT          33
#define IDD_FILTER_CHOOSE               41
#define IDC_STATIC_1                    42
#define IDC_STATIC_2                    43
#define IDC_BUTTON_ADD_ALL              44
#define IDC_BUTTON_ADD                  45
#define IDC_BUTTON_REM                  46
#define IDC_BUTTON_REM_ALL              47
#define IDC_LIST_EXIST                  48
#define IDC_LIST_TO_REMOVE              49
#define IDC_EDIT_TIME_4_TIMER           100
#define IDC_TREEVIEW_INFO               100
#define IDC_SCROLLBAR_VERT_PREVIEW      101
#define IDC_EDIT1                       101
#define IDC_EDIT_INFO_ALARM             101
#define IDC_GROUPBOX1                   101
#define IDC_STATICTEXT_NUM_ON_LB        101
#define IDC_GROUPBOX_1                  101
#define IDC_STATICTEXT_NUM_1            101
#define IDC_PROGRESSBAR                 101
#define IDC_STATICTEXT_G_F1             101
#define IDC_STATICTEXT_TIME_4_TIMER     101
#define IDC_LISTBOX_P_VAR_CHOOSE        101
#define IDC_MY_HAND                     101
#define IDC_NEED_CODE_MSG               101
#define IDC_EDIT_GET_NAME               101
#define IDC_GROUPBOX_DATE_TREE          101
#define IDC_EDIT_SHOW_REC_FROM          101
#define IDD_BASENPSCARD_DIALOG          102
#define IDC_SCROLLBAR_HORZ_PREVIEW      102
#define IDC_EDIT_PSW_L1                 102
#define IDC_BUTTONF_6                   102
#define IDC_GROUPBOX_2                  102
#define IDC_STATICTEXT_NUM_2            102
#define IDC_STATIC_WAIT                 102
#define IDC_STATICTEXT_G_F2             102
#define IDC_PENCIL                      102
#define IDNO_OK                         102
#define IDC_EDIT_DATE_FROM_TREE         102
#define IDC_GROUPBOX_F_ALARM            102
#define IDC_STATICTEXT_NUM_ON_LB2       102
#define IDC_EDIT_SHOW_REC_NUM           102
#define IDS_APP_TITLE                   103
#define IDC_GROUPBOX2                   103
#define IDC_SCROLLBAR_COUNT             103
#define IDC_STATICTEXT_NUM_3            103
#define IDC_BUTTON_PROGRESS_ABORT       103
#define IDC_STATICTEXT_G_F3             103
#define IDC_EDIT_DATE_TO_TREE           103
#define IDM_ABOUT                       104
#define IDC_EDIT_PSW_L2                 104
#define IDC_STATICTEXT_NUM_4            104
#define IDC_STATICTEXT_G_F4             104
#define IDC_BUTTON_ADD_DATE_TREE        104
#define IDC_STATIC_WAIT_COUNT           104
#define IDM_EXIT                        105
#define IDC_EDIT_PSW_L1_C               105
#define IDC_STATICTEXT_NUM_5            105
#define IDC_STATICTEXT_G_F5             105
#define IDC_STATICTEXT_G_FROM           105
#define IDC_GROUPBOX_AVAILABLE_TREE     105
#define IDC_STATIC_WAIT_COUNT2          105
#define IDC_STATIC_WAIT_MAX             105
#define IDC_STATICTEXT_CONF1            106
#define IDC_STATICTEXT_NUM_6            106
#define IDC_STATICTEXT_G_F6             106
#define IDC_STATICTEXT_G_TO             106
#define IDC_LISTBOX_AVAILABLE_TREE      106
#define IDC_STATICTEXT_CONF2            107
#define IDC_STATICTEXT_NUM_7            107
#define IDC_LISTBOX_CHOOSE_LG           107
#define IDC_LISTBOX_CHOOSE_DATE         107
#define IDC_GROUPBOX_CHOOSED_TREE       107
#define IDC_EDIT_PSW_L2_C               108
#define IDC_STATICTEXT_NUM_8            108
#define IDC_EDIT_FROM_DT_EXP            108
#define IDC_LISTBOX_CHOOSED_TREE        108
#define IDC_CHECKBOX_L1                 109
#define IDC_STATICTEXT_NUM_9            109
#define IDC_EDIT_TO_DT_EXP              109
#define IDC_BUTTON_ADD_OPER_TREE        109
#define IDC_CHECKBOX_L2                 110
#define IDC_STATICTEXT_NUM_10           110
#define IDC_BUTTON_REM_OPER_TREE        110
#define IDC_STATICFRAME_LGRAPH1         111
#define IDC_BUTTON_ADDALL_OPER_TREE     111
#define IDC_STATICTEXT_DESCR            112
#define IDC_BUTTON_REMALL_OPER_TREE     112
#define IDC_STATICTEXT_V_MIN            113
#define IDC_BUTTON_REM_DATE_TREE        113
#define IDC_STATICTEXT_V_MAX            114
#define IDC_STATICTEXT_TITLE_OPER_TREE  114
#define IDC_STATICTEXT_DATE_FROM_TREE   115
#define IDC_STATICTEXT_DATE_TO_TREE     116
#define IDC_STATICFRAME_TREE            117
#define IDC_STATIC_F_BY_ID_ALARM        117
#define IDC_LISTBOX_DATE_TREE           118
#define IDC_STATIC_F_BY_ID_GROUP        118
#define IDC_BUTTON_SAVE                 119
#define IDC_GROUPBOX_CHOOSE_REPORT      119
#define IDC_STATIC_F_BY_ID_SECT         119
#define IDC_RADIOBUTTON_OPERATOR        120
#define IDC_STATIC_F_BY_ID_PRPH         120
#define IDC_EDIT_VAL_1                  121
#define IDC_RADIOBUTTON_CAUSE           121
#define IDC_STATIC_TOT_REC_LABEL        121
#define IDC_EDIT_VAL_2                  122
#define IDC_EDIT_TIME_FROM_TREE         122
#define IDC_EDIT_VAL_3                  123
#define IDC_EDIT_TIME_TO_TREE           123
#define IDC_EDIT_VAL_4                  124
#define IDC_RADIOBUTTON_PRINT           124
#define IDC_EDIT_VAL_5                  125
#define IDC_RADIOBUTTON_PREVIEW         125
#define IDC_EDIT_VAL_6                  126
#define IDC_STATICFRAME_1               126
#define IDC_EDIT_VAL_7                  127
#define IDC_GROUPBOX_PRINT              127
#define IDR_MAINFRAME                   128
#define IDC_EDIT_VAL_8                  128
#define IDC_EDIT_VAL_9                  129
#define IDD_CHOOSE_BIT_SEARCH_FILE      129
#define IDC_EDIT_VAL_10                 130
#define IDC_EDIT_VAL_11                 131
#define IDR_242                         131
#define IDC_EDIT_VAL_12                 132
#define IDC_EDIT_VAL_13                 133
#define IDI_ICON_INFO                   133
#define IDC_EDIT_VAL_14                 134
#define IDD_DIALOG1                     134
#define IDD_DIALOG_CHOOSE_RESOLUTION    134
#define IDC_EDIT_VAL_15                 135
#define IDD_RECORD_TO_VIEW              135
#define IDC_EDIT_VAL_16                 136
#define IDC_GROUPBOX_3                  152
#define IDC_GROUPBOX3                   153
#define IDC_EDIT_PSW_L3                 154
#define IDC_STATICTEXT_CONF3            157
#define IDC_EDIT_PSW_L3_C               158
#define IDC_CHECKBOX_L3                 160
#define IDC_EDIT_MIN_1                  181
#define IDC_EDIT_MIN_2                  182
#define IDC_EDIT_MIN_3                  183
#define IDC_EDIT_MIN_4                  184
#define IDC_EDIT_MIN_5                  185
#define IDC_EDIT_MIN_6                  186
#define IDC_EDIT_MIN_7                  187
#define IDC_EDIT_MIN_8                  188
#define IDC_EDIT_MIN_9                  189
#define IDC_EDIT_MIN_10                 190
#define IDC_EDIT_MIN_11                 191
#define IDC_EDIT_MIN_12                 192
#define IDC_EDIT_MIN_13                 193
#define IDC_EDIT_MIN_14                 194
#define IDC_EDIT_MIN_15                 195
#define IDC_EDIT_MIN_16                 196
#define IDC_STATICFRAME_LGRAPH2         201
#define IDC_SCROLLBAR_COUNT_NUM         203
#define IDC_EDIT_MAX_1                  241
#define IDC_EDIT_MAX_2                  242
#define IDC_EDIT_MAX_3                  243
#define IDC_EDIT_MAX_4                  244
#define IDC_EDIT_MAX_5                  245
#define IDC_EDIT_MAX_6                  246
#define IDC_EDIT_MAX_7                  247
#define IDC_EDIT_MAX_8                  248
#define IDC_EDIT_MAX_9                  249
#define IDC_EDIT_MAX_10                 250
#define IDC_EDIT_MAX_11                 251
#define IDC_EDIT_MAX_12                 252
#define IDC_EDIT_MAX_13                 253
#define IDC_EDIT_MAX_14                 254
#define IDC_EDIT_MAX_15                 255
#define IDC_EDIT_MAX_16                 256
#define IDC_EDIT_DESCR_1                301
#define IDC_EDIT_DESCR_2                302
#define IDC_EDIT_DESCR_3                303
#define IDC_EDIT_DESCR_4                304
#define IDC_EDIT_DESCR_5                305
#define IDC_EDIT_DESCR_6                306
#define IDC_EDIT_DESCR_7                307
#define IDC_EDIT_DESCR_8                308
#define IDC_EDIT_DESCR_9                309
#define IDC_EDIT_DESCR_10               310
#define IDC_EDIT_DESCR_11               311
#define IDC_EDIT_DESCR_12               312
#define IDC_EDIT_DESCR_13               313
#define IDC_EDIT_DESCR_14               314
#define IDC_EDIT_DESCR_15               315
#define IDC_EDIT_DESCR_16               316
#define IDC_RADIOBUTTON__640x480        321
#define IDC_RADIOBUTTON__800x600        322
#define IDC_RADIOBUTTON__1024x768       323
#define IDC_RADIOBUTTON__1280x1024      324
#define IDC_RADIOBUTTON__1600x1200      325
#define IDC_RADIOBUTTON__1920x1440      326
#define IDC_RADIOBUTTON__1440x900       327
#define IDC_RADIOBUTTON__1680x1050      328
#define IDC_RADIOBUTTON__RES_PERS       329
#define IDC_EDIT_RES_WIDTH              330
#define IDC_EDIT_RES_HEIGHT             331
#define IDC_GROUPBOX                    332
#define IDD_HEADER2                     500
#define IDD_CONFIG                      502
#define IDD_NEED_CODE                   504
#define IDB_BITMAP_LOGO                 900
#define IDB_BITMAP_LOGO640x480          901
#define IDB_BITMAP_LOGO_MIN             902
#define IDB_BITMAP_SAVE                 903
#define IDB_BITMAP_NOT_SAVE             904
#define IDB_BKG_WAIT                    906
#define IDB_BALL                        907
#define IDB_SAVE                        908
#define IDB_DONE                        909
#define APX_PPR_CURRPAGE                920
#define APX_PPR_NEXT                    921
#define APX_PPR_PREVIOUS                922
#define APX_PPR_DONE                    923
#define IDC_STATIC_SV_TIME              924
#define IDC_STATIC_INIT_DATE            925
#define IDD_CLIENT                      1000
#define IDC_CHECK_DATE                  1000
#define IDD_BASE                        1001
#define IDD_STANDARD                    1001
#define IDC_CHECK_DATE_ORD              1001
#define IDC_REPORT_SETUP                1001
#define IDC_CHECK_REV_ORD               1002
#define IDC_EDIT_INIT_DATE              1002
#define IDD_EMPTY                       1003
#define IDC_CHECK_HISTORY               1003
#define IDC_EDIT_INIT_TIME              1003
#define IDD_MAIN_MENU                   1004
#define IDC_EDIT_END_DATE               1004
#define IDD_HEADER                      1005
#define IDC_EDIT_END_TIME               1005
#define IDD_FOOTER                      1006
#define IDC_STATIC_END_DATE             1006
#define IDD_PSW                         1007
#define IDC_STATIC_INIT_TIME            1007
#define IDD_ALARM                       1008
#define IDC_STATIC_END_TIME             1008
#define IDD_TURN_OVER                   1009
#define IDC_CHECK_ORDER                 1009
#define IDD_WAIT                        1010
#define IDC_EDIT_F_ALARM                1010
#define IDD_SAVED_FILE                  1011
#define IDC_EDIT_F_GRP                  1011
#define IDC_STATIC_SV_VALUE1            1011
#define IDD_SEARCH_FILE                 1012
#define IDC_EDIT_F_SECTION              1012
#define IDC_STATIC_SV_VALUE2            1012
#define IDD_EXPORT                      1013
#define IDC_EDIT_F_PRPH                 1013
#define IDC_STATIC_SV_VALUE3            1013
#define IDC_BUTTON2                     1013
#define IDC_LISTBOX_CHOOSE_PAGE         1013
#define IDD_CHOOSE_NUM                  1014
#define IDC_STATIC_TOT_REC_INFO         1014
#define IDC_STATIC_SV_VALUE4            1014
#define IDC_TREE1                       1014
#define IDD_INPUT_DATE                  1015
#define IDC_STATIC_SV_VALUE5            1015
#define IDC_STATIC_INFO                 1015
#define IDD_PARAM                       1016
#define IDC_STATIC_SV_VALUE6            1016
#define IDC_SPIN1                       1016
#define IDD_LIST_MAINT                  1017
#define IDC_STATIC_SV_VALUE7            1017
#define IDC_CHECK_ADVANCED_REPORT       1017
#define IDD_MANUTENZ                    1018
#define IDC_STATIC_SV_VALUE8            1018
#define IDD_SET_MAINT_TIME              1019
#define IDC_STATIC_SV_VALUE9            1019
#define IDD_NORMALIZ                    1020
#define IDC_STATIC_SV_VALUE10           1020
#define IDC_CHECK_FORCE_RES             1020
#define IDD_NORMALZ                     1021
#define IDC_STATIC_SV_NAME1             1021
#define ID_OK                           1021
#define IDD_CHG_PSW                     1022
#define IDC_STATIC_SV_NAME2             1022
#define IDC_EDIT_NUM_DEC                1022
#define IDD_LGRAPH2                     1023
#define IDC_STATIC_SV_NAME3             1023
#define IDC_BUTTON_RELOAD_DEC           1023
#define IDD_LGRAPH2_LIMITS              1024
#define IDC_STATIC_SV_NAME4             1024
#define IDD_PROGRESS                    1025
#define IDC_STATIC_SV_NAME5             1025
#define IDC_EDIT_FILTER_TEXT_ALARM      1025
#define IDD_CHOOSE_GRAPH                1026
#define IDC_STATIC_SV_NAME6             1026
#define IDC_BUTTON1                     1026
#define IDC_BUTTON_GO_FILTER            1026
#define IDC_BUTTON_AL_TYPE_FILTER       1026
#define IDD_SET_TIME_FOR_TIMER          1027
#define IDC_STATIC_SV_NAME7             1027
#define IDC_BUTTON_AL_SECTION_FILTER    1027
#define IDD_P_VAR_CHOOSE                1028
#define IDC_STATIC_SV_NAME8             1028
#define IDC_STATIC_TEXT_FILTER_AL       1028
#define IDD_RECIPE                      1029
#define IDC_STATIC_SV_NAME9             1029
#define IDC_STATIC_LABEL_TOT_REC        1029
#define IDC_STATIC_SV_NAME10            1030
#define IDC_STATIC_INFO_TOT_REC         1030
#define IDC_STATIC_HEAD_ALARM           1030
#define IDC_STATIC_SV_VALUE_COLOR1      1031
#define IDC_STATIC_LABEL_SHOW_REC       1031
#define IDC_STATIC_SV_VALUE_COLOR2      1032
#define IDC_STATIC_LABEL_SHOW_NUMREC    1032
#define IDC_STATIC_SV_VALUE_COLOR3      1033
#define IDC_STATIC_SV_VALUE_COLOR4      1034
#define IDC_STATIC_SV_VALUE_COLOR5      1035
#define IDC_STATIC_SV_VALUE_COLOR6      1036
#define IDC_STATIC_SV_VALUE_COLOR7      1037
#define IDC_STATIC_SV_VALUE_COLOR8      1038
#define IDC_STATIC_SV_VALUE_COLOR9      1039
#define IDD_RECIPE_ROW                  1040
#define IDC_STATIC_SV_VALUE_COLOR10     1040
#define IDD_MODELESS_BODY               1041
#define IDD_MODAL_BODY                  1042
#define IDD_SHOW_INFO_ALARM             1043
#define IDC_EDIT_PSW                    1101
#define IDC_LISTBOX_ALARM               1101
#define IDC_EDIT_DA_ORE                 1101
#define IDC_STATICTEXT_WAIT             1101
#define IDC_STATICTEXT_SAVED_FILE       1101
#define IDC_LISTBOX_CHOOSE_FILE         1101
#define IDC_LISTBOX_CHOOSE_EXP          1101
#define IDC_STATIC_FROM                 1101
#define IDC_EDIT_INP_DATE_FROM          1101
#define IDC_STATICTEXT_BAUDRATE         1101
#define IDC_LB_MAINT                    1101
#define IDC_LISTBOX_MANUTENZ            1101
#define IDC_EDIT_MAINT_HOURS            1101
#define IDC_GROUPBOX_NRM1               1101
#define IDC_STATICTEXT_SHOW_REP         1102
#define IDC_EDIT_A_ORE                  1102
#define IDC_ANIMATION_WAIT              1102
#define IDC_STATICBITMAP_SAVE           1102
#define IDC_STATIC_TO                   1102
#define IDC_EDIT_INP_DATE_TO            1102
#define IDC_STATICTEXT_DATALEN          1102
#define IDC_EDIT_INFO_MANUT             1102
#define IDC_EDIT_MAINT_MINUTES          1102
#define IDC_GROUPBOX_NRM2               1102
#define IDC_STATICTEXT_RESET_AL         1103
#define IDC_EDIT_ID_TURN                1103
#define IDC_STATICBITMAP_NOT_SAVE       1103
#define IDC_EDIT_FROM                   1103
#define IDC_STATICTEXT_INP_FROM         1103
#define IDC_STATICTEXT_PARITY           1103
#define IDC_EDIT_ORE_MANUT              1103
#define IDC_STATICTEXT_MAINT_HOURS      1103
#define IDC_GROUPBOX_SET_VALORI         1103
#define IDC_STATICTEXT_AL_EXIT          1104
#define IDC_COMBOBOX_TURN               1104
#define IDC_EDIT_TO                     1104
#define IDC_STATICTEXT_INP_TO           1104
#define IDC_STATICTEXT_BITSTOP          1104
#define IDC_STATICTEXT_MAINT_MINUTES    1104
#define IDC_STATICFRAME_AL_F1           1105
#define IDC_LISTBOX_TURN                1105
#define IDC_STATIC_MAX                  1105
#define IDC_EDIT_YEAR_FROM              1105
#define IDC_COMBOBOX_BAUDRATE           1105
#define IDC_STATIC_NRM1                 1105
#define IDC_STATICTEXT_INP_FROM4        1105
#define IDC_STATICTEXT_DATEINFO         1105
#define IDC_STATICFRAME_AL_F2           1106
#define IDC_BUTTON_ADD_TURN             1106
#define IDC_INFO_MAX                    1106
#define IDC_EDIT_YEAR_TO                1106
#define IDC_COMBOBOX_DATA_LEN           1106
#define IDC_STATIC_NRM2                 1106
#define IDC_STATICFRAME_AL_F3           1107
#define IDC_BUTTON_DEL_TURN             1107
#define IDC_COMBOBOX_PARITY             1107
#define IDC_STATIC_NRM3                 1107
#define IDC_EDIT_INP_TIME_FROM          1107
#define IDC_STATICFRAME_AL_F4           1108
#define IDC_BUTTON_MOD_TURN             1108
#define IDC_COMBOBOX_BITSTOP            1108
#define IDC_STATIC_NRM4                 1108
#define IDC_EDIT_INP_TIME_TO            1108
#define IDC_RADIOBUTTON_NO_REP          1109
#define IDC_STATICTEXT_TURN_NUM         1109
#define IDC_STATIC_NRM5                 1109
#define IDC_STATICTEXT_INP_FROM2        1109
#define IDC_STATICTEXT_PARITY2          1109
#define IDB_BKG_TOOLBAR                 1110
#define IDC_RADIOBUTTON_ONLY_ALARM      1110
#define IDC_STATICTEXT_TURN_DA_A        1110
#define IDC_STATIC_NRM6                 1110
#define IDC_STATICTEXT_INP_FROM3        1110
#define IDC_STATICTEXT_BITSTOP2         1110
#define IDB_TOOLBAR_PREVIEW             1111
#define IDC_RADIOBUTTON_ALL_REPORT      1111
#define IDC_STATICTEXT_TURN_TYPE        1111
#define IDC_STATIC_NRM7                 1111
#define IDC_COMBOBOX_DTR_DSR            1111
#define IDD_PREVIEW                     1112
#define IDC_LISTBOX_REPORT              1112
#define IDC_STATIC_NRM8                 1112
#define IDC_COMBOBOX_RTS_CTS            1112
#define IDD_INPUT_TIME                  1113
#define IDC_STATIC_NRM9                 1113
#define IDC_STATICTEXT_BITSTOP3         1113
#define IDC_STATIC_NRM10                1114
#define IDC_COMBOBOX_RTS_CTS2           1114
#define IDC_COMBOBOX_XON_XOFF           1114
#define IDC_STATIC_NRM11                1115
#define IDC_STATIC_NRM12                1116
#define IDC_STATIC_NRM_N1               1120
#define IDC_STATIC_NRM_N2               1121
#define IDC_STATIC_NRM_N3               1122
#define IDC_STATIC_NRM_N4               1123
#define IDC_STATIC_NRM_N5               1124
#define IDC_STATIC_NRM_N6               1125
#define IDC_STATIC_NRM_N7               1126
#define IDC_STATIC_NRM_N8               1127
#define IDC_STATIC_NRM_N9               1128
#define IDC_STATIC_NRM_N10              1129
#define IDC_STATIC_NRM_N11              1130
#define IDC_STATIC_NRM_N12              1131
#define IDC_STATIC_NRM_N13              1132
#define IDC_STATIC_NRM_N14              1133
#define IDC_STATIC_NRM_N15              1134
#define IDC_STATIC_NRM_N16              1135
#define IDC_STATIC_NRM_N17              1136
#define IDC_STATIC_NRM_N18              1137
#define IDC_STATIC_NRM_N19              1138
#define IDC_STATIC_NRM_N20              1139
#define IDC_STATICFRAME_NRM1            1140
#define IDC_STATICFRAME_NRM2            1141
#define IDC_EDIT_MAX_POWER1             1145
#define IDC_EDIT_MAX_POWER2             1146
#define IDC_EDIT_MAX_POWER3             1147
#define IDC_EDIT_MAX_POWER4             1148
#define IDC_EDIT_MAX_POWER5             1149
#define IDC_EDIT_MAX_POWER6             1150
#define IDC_EDIT_MAX_POWER7             1151
#define IDC_EDIT_MAX_POWER8             1152
#define IDC_EDIT_MAX_POWER9             1153
#define IDC_EDIT_MAX_POWER10            1154
#define IDC_EDIT_MAX_POWER11            1155
#define IDC_EDIT_MAX_POWER12            1156
#define IDC_EDIT_MAX_POWER13            1157
#define IDC_EDIT_MAX_POWER14            1158
#define IDC_EDIT_MAX_POWER15            1159
#define IDC_EDIT_MAX_POWER16            1160
#define IDC_EDIT_MAX_POWER17            1161
#define IDC_EDIT_MAX_POWER18            1162
#define IDC_EDIT_MAX_POWER19            1163
#define IDC_EDIT_MAX_POWER20            1164
#define IDC_EDIT_BOTTOM_1               1165
#define IDC_EDIT_BOTTOM_2               1166
#define IDC_EDIT_BOTTOM_3               1167
#define IDC_EDIT_BOTTOM_4               1168
#define IDC_EDIT_NORM_1                 1170
#define IDC_EDIT_NORM_2                 1171
#define IDC_EDIT_NORM_3                 1172
#define IDC_EDIT_NORM_4                 1173
#define IDC_EDIT_NORM_5                 1174
#define IDC_EDIT_NORM_6                 1175
#define IDC_EDIT_NORM_7                 1176
#define IDC_EDIT_NORM_8                 1177
#define IDC_BUTTON_SAVE_TO_FILE         1180
#define IDC_BUTTON_READ_FROM_FILE       1181
#define IDC_BUTTON_RECEIVE_FROM_PLC     1182
#define IDC_BUTTON_SEND_TO_PLC          1183
#define IDC_RADIOBUTTON_MAX_POWER       1190
#define IDC_RADIOBUTTON_MAX_SPEED       1191
#define IDC_RADIOBUTTON_NORM_SPEED      1192
#define IDC_PROMPT_DATA                 1200
#define IDC_EDIT_V_MIN_1                1201
#define IDC_PROMPT_TIME                 1201
#define IDC_EDIT_V_MIN_2                1202
#define IDC_PROMPT_LINE_SPEED           1202
#define IDC_EDIT_V_MIN_3                1203
#define IDC_PROMPT_MOT_SPEED            1203
#define IDC_EDIT_V_MIN_4                1204
#define IDC_PROMPT_POWER                1204
#define IDC_EDIT_V_MIN_5                1205
#define IDC_PROMPT_SCORR                1205
#define IDC_EDIT_V_MIN_6                1206
#define IDC_PROMPT_MOT_KW               1206
#define IDC_EDIT_V_MIN_7                1207
#define IDC_PROMPT_TOT_KW               1207
#define IDC_EDIT_V_MIN_8                1208
#define IDC_STATICTEXT_DA_LG            1208
#define IDC_EDIT_V_MIN_9                1209
#define IDC_STATICTEXT_A_LG             1209
#define IDC_EDIT_V_MIN_10               1210
#define IDC_STATICTEXT_MIN1             1210
#define IDC_STATICTEXT_1                1211
#define IDC_STATICTEXT_MAX1             1211
#define IDC_STATICTEXT_2                1212
#define IDC_STATICTEXT_MIN2             1212
#define IDC_STATICTEXT_3                1213
#define IDC_STATICTEXT_MAX2             1213
#define IDC_STATICTEXT_4                1214
#define IDC_STATICTEXT_MIN3             1214
#define IDC_STATICTEXT_5                1215
#define IDC_STATICTEXT_MAX3             1215
#define IDC_STATICTEXT_6                1216
#define IDC_EDIT_DATA_FROM              1216
#define IDC_STATICTEXT_7                1217
#define IDC_EDIT_DATA_TO                1217
#define IDC_STATICTEXT_8                1218
#define IDC_EDIT_TIME_FROM              1218
#define IDC_STATICTEXT_9                1219
#define IDC_EDIT_TIME_TO                1219
#define IDC_STATICTEXT_10               1220
#define IDC_EDIT_LINE_SPEED_FROM        1220
#define IDC_STATICTEXT_11               1221
#define IDC_EDIT_LINE_SPEED_TO          1221
#define IDC_STATICTEXT_12               1222
#define IDC_EDIT_OVEN_SPEED_FROM        1222
#define IDC_STATICTEXT_13               1223
#define IDC_EDIT_OVEN_SPEED_TO          1223
#define IDC_STATICTEXT_14               1224
#define IDC_EDIT_POWER_FROM             1224
#define IDC_STATICTEXT_15               1225
#define IDC_EDIT_POWER_TO               1225
#define IDC_STATICTEXT_16               1226
#define IDC_EDIT_TENSION_FROM           1226
#define IDC_EDIT_TENSION_TO             1227
#define IDC_EDIT_O_POWER_FROM           1228
#define IDC_EDIT_O_POWER_TO             1229
#define IDC_EDIT_TOT_MT_FROM            1230
#define IDC_EDIT_TOT_MT_TO              1231
#define IDC_EDIT_V_MAX_1                1301
#define IDC_EDIT_V_MAX_2                1302
#define IDC_EDIT_V_MAX_3                1303
#define IDC_EDIT_V_MAX_4                1304
#define IDC_EDIT_V_MAX_5                1305
#define IDC_EDIT_V_MAX_6                1306
#define IDC_EDIT_V_MAX_7                1307
#define IDC_EDIT_V_MAX_8                1308
#define IDC_EDIT_V_MAX_9                1309
#define IDC_EDIT_V_MAX_10               1310
#define IDC_STATIC_DESCR_LIMITS_1       1401
#define IDC_STATIC_DESCR_LIMITS_2       1402
#define IDC_STATIC_DESCR_LIMITS_3       1403
#define IDC_STATIC_DESCR_LIMITS_4       1404
#define IDC_STATIC_DESCR_LIMITS_5       1405
#define IDC_STATIC_DESCR_LIMITS_6       1406
#define IDC_STATIC_DESCR_LIMITS_7       1407
#define IDC_STATIC_DESCR_LIMITS_8       1408
#define IDC_STATIC_DESCR_LIMITS_9       1409
#define IDC_STATIC_DESCR_LIMITS_10      1410
#define IDC_STATICBITMAP_LOGO           2001
#define IDC_BUTTON_F1                   2101
#define IDC_BUTTON_F2                   2102
#define IDC_BUTTON_F3                   2103
#define IDC_BUTTON_F4                   2104
#define IDC_BUTTON_F5                   2105
#define IDC_BUTTON_F6                   2106
#define IDC_BUTTON_F7                   2107
#define IDC_BUTTON_F8                   2108
#define IDC_BUTTON_F9                   2109
#define IDC_BUTTON_F10                  2110
#define IDC_BUTTON_F11                  2111
#define IDC_BUTTON_F12                  2112
#define IDC_CHECKBOX_USE_MOUSE          2190
#define IDC_CHECKBOXSHUTDOWN            2191
#define IDC_CHECKBOX_NUMLOCK            2192
#define IDC_BUTTON_CFG_NORM             2193
#define IDC_BUTTON_TURN                 2194
#define IDC_CHECKBOX_HIDE_TASKBAR       2195
#define IDC_CHECKBOX_NO_ALT_KEY         2196
#define IDC_CHECKBOX_NO_CTRL            2197
#define IDC_CHECKBOX_NO_WINKEY          2198
#define IDC_CHECKBOX_USE_READER         2199
#define IDC_CHECKBOX_PERIF1             2200
#define IDC_CHECKBOX_PERIF2             2201
#define IDC_CHECKBOX_PERIF3             2202
#define IDC_CHECKBOX_PERIF4             2203
#define IDC_CHECKBOX_PERIF5             2204
#define IDC_CHECKBOX_PERIF6             2205
#define IDC_CHECKBOX_PERIF7             2206
#define IDC_CHECKBOX_PERIF8             2207
#define IDC_CHECKBOX_NO_DLL             2208
#define IDC_CHECKBOX_NO_POWEROFF        2209
#define IDC_COMBOBOX_PRG_PERIF1         2210
#define IDC_COMBOBOX_PRG_PERIF2         2211
#define IDC_COMBOBOX_PRG_PERIF3         2212
#define IDC_COMBOBOX_PRG_PERIF4         2213
#define IDC_COMBOBOX_PRG_PERIF5         2214
#define IDC_COMBOBOX_PRG_PERIF6         2215
#define IDC_COMBOBOX_PRG_PERIF7         2216
#define IDC_COMBOBOX_PRG_PERIF8         2217
#define IDC_COMBOBOX_COM_PERIF1         2220
#define IDC_COMBOBOX_COM_PERIF2         2221
#define IDC_COMBOBOX_COM_PERIF3         2222
#define IDC_COMBOBOX_COM_PERIF4         2223
#define IDC_COMBOBOX_COM_PERIF5         2224
#define IDC_COMBOBOX_COM_PERIF6         2225
#define IDC_COMBOBOX_COM_PERIF7         2226
#define IDC_COMBOBOX_COM_PERIF8         2227
#define IDC_BUTTON_PARA_PERIF1          2230
#define IDC_BUTTON_PARA_PERIF2          2231
#define IDC_BUTTON_PARA_PERIF3          2232
#define IDC_BUTTON_PARA_PERIF4          2233
#define IDC_BUTTON_PARA_PERIF5          2234
#define IDC_BUTTON_PARA_PERIF6          2235
#define IDC_BUTTON_PARA_PERIF7          2236
#define IDC_BUTTON_PARA_PERIF8          2237
#define IDC_GROUPBOX_CFG1               2240
#define IDC_GROUPBOX_CFG2               2241
#define IDC_GROUPBOX_CFG3               2242
#define IDC_STATICFRAME_CFG7            2251
#define IDC_STATICFRAME_CFG8            2252
#define IDC_STATICFRAME_CFG9            2253
#define IDC_EDIT_OFFSET_PRF1            2285
#define IDC_EDIT_OFFSET_PRF2            2286
#define IDC_EDIT_OFFSET_PRF3            2287
#define IDC_EDIT_OFFSET_PRF4            2288
#define IDC_EDIT_OFFSET_PRF5            2289
#define IDC_EDIT_OFFSET_PRF6            2290
#define IDC_EDIT_OFFSET_PRF7            2291
#define IDC_EDIT_OFFSET_PRF8            2292
#define IDC_EDIT_NUM_EXTENDED_PRF_ONMEM 2293
#define IDC_CHECK_HIDE_SHOW_DRIVER      2296
#define IDC_STATICTEXT_LANG             2300
#define IDC_COMBOBOX_LANG               2301
#define IDC_STATICTEXT_LANG2            2302
#define IDD_GET_NAME                    4326
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
