//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pAppl.rc
//
#define IDB_DONE                        1
#define IDI_ICON1                       1
#define IDD_CLIENT                      1
#define IDB_OPEN                        2
#define IDD_CL_ADR                      2
#define IDB_SAVE                        3
#define IDD_CL_SVTEST                   3
#define IDD_DIALOG_FILL                 4
#define IDB_CLEAR                       4
#define IDD_DIALOG_VERIFY               5
#define IDB_FILL                        5
#define IDD_DIALOG_SHOW_TYPE            6
#define IDB_OK                          6
#define IDD_DIALOG_SHOW_ACTION          7
#define IDB_CANC                        7
#define IDD_DIALOG_COPY                 8
#define IDB_FILL_HANDLE                 8
#define IDB_WRITE                       9
#define IDB_READ                        10
#define IDB_TABS                        11
#define IDB_REFRESH                     12
#define IDB_COPY                        13
#define IDC_COMBOBOX_TYPE               101
#define IDC_STATICTEXT_1                101
#define IDC_STATIC_INFO_VERIFY          101
#define IDD_DIALOG_HANDLE               101
#define IDC_EDIT_FILL_DB                102
#define IDC_STATICTEXT_2                102
#define IDD_DIALOG_CLEAR                102
#define IDC_COMBOBOX_ACTION             103
#define IDC_STATICTEXT_3                103
#define IDC_STATICTEXT1                 104
#define IDC_STATICTEXT_4                104
#define IDC_EDIT_FILL_START             105
#define IDC_STATICTEXT_5                105
#define IDC_EDIT_FILL_ADDRESS           106
#define IDC_STATICTEXT_6                106
#define IDC_EDIT_FILL_LEN               107
#define IDC_STATICTEXT_7                107
#define IDC_STATICTEXT2                 108
#define IDC_STATICTEXT_8                108
#define IDC_STATICTEXT5                 109
#define IDC_STATICTEXT_9                109
#define IDC_STATICTEXT4                 109
#define IDC_EDIT_FILL_STEP              110
#define IDC_STATICTEXT_10               110
#define IDC_EDIT_COPY_START2            110
#define IDC_CHECKBOX_DB                 111
#define IDC_STATICTEXT_11               111
#define IDC_CHECKBOX_ADDRESS            112
#define IDC_STATICTEXT_12               112
#define IDC_CHECKBOX_TYPE               113
#define IDC_STATICTEXT_13               113
#define IDC_CHECKBOX_COPY_FROM          113
#define IDC_CHECKBOX_ACTION             114
#define IDC_STATICTEXT_14               114
#define IDC_CHECKBOX_OFFSET             114
#define IDC_STATICFRAME1                115
#define IDC_STATICTEXT_15               115
#define IDC_CHECKBOX_IP                 116
#define IDC_STATICTEXT_16               116
#define IDC_STATICFRAME3                116
#define IDC_EDIT_FILL_IP_1              117
#define IDC_BUTTON_OPEN                 117
#define IDC_STATICTEXT7                 117
#define IDC_CHECKBOX_ADDRESS2           117
#define IDC_CHECKBOX_ADDRESS_PROGR      117
#define IDC_EDIT_FILL_IP_2              118
#define IDC_CHECKBOX_ZERO               118
#define IDC_LISTBOX_VERIFY              118
#define IDC_EDIT_FILL_STEP_DB           118
#define IDC_EDIT_FILL_IP_3              119
#define IDC_BUTTON_SAVE                 119
#define IDC_LISTBOX_VERIFY2             119
#define IDC_STATICFRAME4                119
#define ID_OK                           120
#define IDC_BUTTON_SAVE_AS              120
#define ID_CANCEL                       121
#define IDC_BUTTON_CLEAR                121
#define IDC_EDIT_FILL_IP_4              122
#define IDC_STATICTEXT_NUM              122
#define IDC_CHECKBOX_MIN                123
#define IDC_EDIT_MAX_ROW                123
#define IDC_EDIT_FILL_MIN               124
#define IDC_BUTTON_FILL                 124
#define IDC_CHECKBOX_MAX                125
#define IDC_GROUPBOX1                   125
#define IDC_EDIT_FILL_MAX               126
#define IDC_RADIOBUTTON_BYTE            126
#define IDC_RADIOBUTTON_WORD            127
#define IDC_STATICTEXT6                 127
#define IDC_RADIOBUTTON_DWORD           128
#define IDC_EDIT_FILL_STEP_LOGIC        128
#define IDC_STATICTEXT3                 129
#define IDC_CHECKBOX_PORT               129
#define IDC_STATICTEXT8                 129
#define IDC_COMBOBOX_DEF_DATA_TYPE      130
#define IDC_EDIT_FILL_PORT              130
#define IDC_EDIT_COPY_N_BLOCK           130
#define IDC_STATICFRAME2                131
#define IDC_CHECKBOX_MAX_P              131
#define IDC_STATICTEXT9                 131
#define IDC_BUTTON_VERIFY               132
#define IDC_EDIT_FILL_MAX_P             132
#define IDC_EDIT_COPY_OFFS_BLOCK        132
#define IDC_EDIT_FILL_MIN_P             133
#define IDC_STATICTEXT_NUM2             133
#define IDC_STATICTEXT_TIMER            133
#define IDC_STATIC_IP_PORT              134
#define IDC_STATIC_IP                   134
#define IDC_CHECKBOX_MAX2               134
#define IDC_CHECKBOX_DESCR              134
#define IDC_CHECKBOX_MIN_P              135
#define IDC_EDIT_TIMER                  135
#define IDC_TAB1                        136
#define IDC_EDIT_FILL_DESCR             136
#define IDC_CHECKBOX_STEP1              136
#define IDC_BUTTON_ADD_TAB              137
#define IDC_BUTTON_CLEAR2               137
#define IDC_BUTTON_COPY                 137
#define IDC_BUTTON_REM_TAB              138
#define IDC_BUTTON_TOGGLE_VIS           139
#define IDC_CHECKBOX_OFFSET_ADDR        139
#define IDC_BUTTON_WRITE                140
#define IDC_EDIT_FILL_OFFSET_ADDR       140
#define IDC_BUTTON_READ                 141
#define IDC_BUTTON_AUTO_REFRESH         142
#define IDC_CHECK_HEX                   143
#define IDC_BUTTON_SVISOR_SEARCH        144
#define IDC_STATIC_HW_SV                145
#define IDC_LIST1                       146
#define IDC_LIST_SV                     146
#define IDC_CHECK_CLEAR_ALL             147
#define IDC_EDIT_CLEAR_FROM             148
#define IDC_EDIT2                       149
#define IDC_EDIT_CLEAR_TO               149
#define IDC_CHECK1                      149
#define IDC_CHECK_FILL_SETUP            149
#define IDC_CHECK_CRYPTED               149
#define IDC_CHECK_MOVE                  149
#define IDC_CHECK_READ                  150
#define IDC_CHECK_CRYPTED2              150
#define IDC_CHECK_HEX_ADDR              150
#define IDC_CHECK_NO_ACTION             150
#define IDC_CHECK_WRITE                 151
#define IDC_CHECK_TYPE1                 151
#define IDC_CHECK_REQUEST               152
#define IDC_CHECK_TYPE2                 152
#define IDC_STATIC_DESCR                152
#define IDC_CHECK_SETUP                 153
#define IDC_CHECK_TYPE3                 153
#define IDC_IPADDRESS                   153
#define IDC_CHECK_TYPE4                 154
#define IDC_EDIT_COPY_START             154
#define IDC_CHECK_TYPE5                 155
#define IDC_EDIT_COPY_LEN               155
#define IDC_CHECK_TYPE6                 156
#define IDC_EDIT_COPY_DB                156
#define IDC_CHECK_TYPE7                 157
#define IDC_EDIT_COPY_ADDRESS           157
#define IDC_CHECK_TYPE8                 158
#define IDC_COMBO_COPY_FROM             158
#define IDC_CHECK_TYPE9                 159
#define IDC_CHECK_FORCE_FILL            159
#define IDC_CHECK_TYPE10                160
#define IDC_RADIO_OVERWRITE             160
#define IDC_CHECK_TYPE11                161
#define IDC_RADIO_PREFIX                161
#define IDC_CHECK_TYPE12                162
#define IDC_RADIO_SUFFIX                162
#define IDC_CHECK_TYPE13                163
#define IDC_CHECK_TYPE14                164
#define IDC_CHECK_TYPE15                165
#define IDC_EDIT_GOTO_ROW               166
#define IDC_BUTTON_GOTO_ROW             167
#define IDC_BUTTON_CLIPBOARD            168
#define IDC_BUTTON_SEARCH_TEXT          169
#define IDC_EDIT_SEARCH_TEXT            170
#define IDC_GROUPBOX_1                  201
#define IDC_GROUPBOX_2                  202
#define IDC_SCROLLBAR_COUNT             203
#define ID_EXIT_APP                     12345
#define ID_UNLOCK                       12346
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         161
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
