//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by maker.rc
//
#define IDI_ICON1                       1
#define IDC_LISTBOX_FONT_ALLOCATED      101
#define IDC_EDIT_ASCII                  101
#define IDC_ALL                         101
#define IDR_ACCELERATOR1                101
#define IDD_DIALOG_PROJECT              101
#define IDC_BUTTON_ADD_FONT             102
#define IDC_RADIO_ASCII                 102
#define IDC_SKIP                        102
#define IDD_OFFSCREEN                   102
#define IDD_CHOOSE_FONT                 103
#define IDC_BUTTON_MOD_FONT             103
#define IDC_RADIO_HEX                   103
#define IDC_APPLY                       103
#define IDD_DIALOG_NEW_DIM              104
#define IDC_BUTTON_REM_FONT             104
#define IDC_EDIT_HEX                    104
#define IDC_INFO_OBJ                    104
#define IDC_SKIP_ALL                    104
#define IDC_BUTTON_UPD_FONT             105
#define IDC_STATIC_PRG                  105
#define IDD_GET_KEY_USER                105
#define IDC_APPLY_ALL                   105
#define IDD_CALIBRATE                   106
#define IDD_DIALOG_RECT_PROP            107
#define IDD_DIALOG_DRAW_PROP            108
#define IDD_DIALOG_LINE_PROP            109
#define IDD_DIALOG_TEXT_PROP            110
#define IDD_DIALOG_IMG_PROP             111
#define IDD_DIALOG_TEXT_PROP_2          112
#define IDD_GET_DATA_ID                 113
#define IDD_DIALOG_LINKED               114
#define IDD_DIALOG_ACTION               115
#define IDC_CURSOR_PAN                  163
#define IDC_CURSOR_PAN_MOVE             164
#define IDD_DIALOG_VARS                 168
#define IDD_DIALOG_UNION_PROP           169
#define IDD_DIALOG1                     170
#define IDD_DIALOG_OFFSET               170
#define IDB_BKG                         200
#define IDB_TOOLBAR                     201
#define IDB_TOOLBAR_ACTION              202
#define IDB_TOOLBAR_PROJECT             203
#define IDB_TOOLBAR_CHG_PAGE            204
#define IDB_OK                          205
#define IDB_CANC                        206
#define IDB_SAVE                        207
#define IDC_SLIDER1                     1368
#define IDC_EDIT1                       1369
#define IDC_BUTTON_CHOOSE_PATH          1370
#define IDC_EDIT_Y                      1370
#define IDC_SLIDER2                     1370
#define IDC_EDIT_TEMPLATE               1371
#define IDC_EDIT_W                      1371
#define IDC_EDIT2                       1371
#define IDC_BUTTON_CHOOSE_TEMPLATE      1372
#define IDC_EDIT_H                      1372
#define IDC_EDIT_TEMPL_DATA             1373
#define IDC_EDIT_CY                     1373
#define IDC_EDIT_IMG_FILE               1373
#define IDC_EDIT_dX                     1373
#define IDC_BUTTON3                     1374
#define IDC_BUTTON_CHOOSE_TEMPL_DATA    1374
#define IDC_EDIT_LINE_TICKNESS          1374
#define IDC_EDIT_dY                     1374
#define IDC_EDIT_WIDTH                  1375
#define IDC_EDIT_HEIGHT                 1376
#define IDC_EDIT_cY2                    1376
#define IDC_CHECK_MODIFY                1377
#define IDC_EDIT_PEN_TICKNESS           1377
#define IDC_EDIT_BASEPATH               1378
#define IDC_EDIT_X                      1379
#define IDC_STATIC_COL_LINE             1380
#define IDC_BUTTON_COL_LINE             1381
#define IDC_STATIC_COL_BKG              1382
#define IDC_BUTTON_COL_BKG              1383
#define IDC_BUTTON_CHOOSE_VAR           1384
#define IDC_EDIT_CX                     1385
#define IDC_STATIC_FONT                 1385
#define IDC_COMBO_LINE_TYPE             1386
#define IDC_COMBO_BKG_TYPE              1387
#define IDC_CHECK_NO_BKG                1387
#define IDC_RADIO_SIMPLE                1388
#define IDC_RADIO_FROM_VAR              1389
#define IDC_EDIT_NUM_VAR                1390
#define IDC_BUTTON_CHOOSE_FONT          1391
#define IDC_RADIO_AL_SX                 1392
#define IDC_RADIO_AL_CENTER             1393
#define IDC_RADIO_AL_DX                 1394
#define IDC_RADIO_AL_TOP                1395
#define IDC_RADIO_AL_MID                1396
#define IDC_RADIO_AL_BOTTOM             1397
#define IDC_EDIT_TEXT                   1398
#define IDC_EDIT_NUM_VAR2               1399
#define IDC_EDIT_ANGLE                  1399
#define IDC_BUTTON_CHOOSE_BMP           1399
#define IDC_CHECK_TXT_ON_BOX            1400
#define IDC_CHECK_TXT_ON_BOX2           1401
#define IDC_CHECK_TXT_MULTILINE         1401
#define IDC_RADIO_DIRECT                1401
#define IDC_RADIO2                      1402
#define IDC_RADIO_BY_VAL                1402
#define IDC_EDIT_ID                     1403
#define IDC_EDIT_ADDR                   1404
#define IDC_EDIT_N_DEC                  1405
#define IDC_EDIT_LEN                    1406
#define IDC_EDIT_OFFS                   1407
#define IDC_EDIT_NORM                   1408
#define IDC_EDIT_ID_TXT                 1409
#define IDC_COMBO_PRPH                  1410
#define IDC_COMBO_TYPE                  1411
#define IDC_LISTVIEW_VAR                1412
#define IDC_LISTVIEW_TEXT               1413
#define IDC_BUTTON_ADD                  1414
#define IDC_BUTTON_REM                  1415
#define IDC_EDIT_IDS                    1415
#define IDC_BUTTON_PLUS                 1416
#define IDC_CHECK_X                     1416
#define IDC_BUTTON_MINUS                1417
#define IDC_CHECK_Y                     1417
#define IDC_EDIT_NBIT                   1418
#define IDC_CHECK_W                     1418
#define IDC_CHECK_H                     1419
#define IDC_BUTTON_COPY                 1419
#define IDC_CHECK_dX                    1420
#define IDC_BUTTON_PASTE                1420
#define IDC_CHECK_dY                    1421
#define IDC_CHECK_cX                    1422
#define IDC_CHECK_cY                    1423
#define IDC_EDIT_cX2                    1424
#define IDC_CHECK_PEN_COLOR             1425
#define IDC_BUTTON_PEN_COLOR            1426
#define IDC_STATIC_PEN_COLOR            1427
#define IDC_CHECK_PEN_TYPE              1428
#define IDC_COMBO_PEN_TYPE              1429
#define IDC_CHECK_PEN_TICKNESS          1430
#define IDC_CHECK_BRUSH_COLOR           1431
#define IDC_STATIC_BRUSH_COLOR          1432
#define IDC_BUTTON_BRUSH_COLOR          1433
#define IDC_CHECK_BRUSH_TYPE            1434
#define IDC_COMBO_BRUSH_TYPE            1435
#define IDC_CHECK_TEXT_COLOR            1436
#define IDC_STATIC_TEXT_COLOR           1437
#define IDC_BUTTON_TEXT_COLOR           1438
#define IDC_RADIO_TEXT_SX               1439
#define IDC_CHECK_RET_ID                1440
#define IDC_EDIT_OFFSET                 1441
#define IDC_CHECK_TEXT_FONT             1442
#define IDC_EDIT_LINKED                 1442
#define IDC_STATIC_TEXT_FONT            1443
#define IDC_BUTTON_CHOOSE_LINKED        1443
#define IDC_BUTTON_TEXT_FONT            1444
#define IDC_STATIC_INFO_VARID           1444
#define IDC_CHECK_TEXT_AL_HORZ          1445
#define IDC_RADIO_TEXT_CENTER           1446
#define IDC_RADIO_TEXT_DX               1447
#define IDC_CHECK_TEXT_AL_VERT          1448
#define IDC_RADIO_TEXT_TOP              1449
#define IDC_RADIO_TEXT_MIDDLE           1450
#define IDC_RADIO_TEXT_DX2              1451
#define IDC_RADIO_TEXT_BOTTOM           1451
#define IDCM_COPY                       10001
#define IDCM_PASTE                      10002
#define IDCM_UNDO                       10003
#define IDCM_FLUSH                      10004
#define IDCM_AD4                        10005
#define IDCM_ADDR_OFFSET                10006
#define IDCM_DUP                        40012
#define IDCM_LOCK                       40014
#define IDCM_HIDE                       40015
#define IDCM_PROP                       40017
#define IDCM_OFFSET                     40019
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1445
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
