//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da resource.rc
//
#define IDI_ICON1                       1
#define IDD_CLIENT                      1
#define IDB_BITMAP_SEND                 3
#define IDC_BUTTON_LOAD                 3
#define IDC_BUTTON_UPLOAD               3
#define IDB_BITMAP_DONE                 4
#define IDC_BUTTON_LOAD2                4
#define IDC_BUTTON_DELETE               4
#define IDC_BUTTON_DOWNLOAD             4
#define IDD_PARAM                       5
#define IDC_BUTTON_RELOAD               5
#define IDB_BITMAP_DEF                  6
#define IDB_BITMAP_CANC                 7
#define IDB_BITMAP_OK                   8
#define IDB_BITMAP_LOAD                 9
#define ID_IMAGE_LAN                    20
#define ID_IMAGE_SAVE                   21
#define ID_IMAGE_SETUP                  22
#define ID_IMAGE_EMAIL                  23
#define ID_IMAGE_LOG                    24
#define ID_IMAGE_USERS                  25
#define ID_IMAGE_DONE                   26
#define ID_IMAGE_RED_SEM                27
#define ID_IMAGE_GREEN_SEM              28
#define ID_IMAGE_TIMING                 29
#define IDD_DIALOG_BACKUP               100
#define IDD_PROGRESS                    101
#define IDC_STATICTEXT_BAUDRATE         101
#define IDC_STATICTEXT_DATALEN          102
#define IDC_STATICTEXT_PARITY           103
#define IDC_STATICTEXT_BITSTOP          104
#define IDD_DIALOG_LAN                  104
#define IDC_COMBOBOX_BAUDRATE           105
#define IDD_DIALOG_TIMING               105
#define IDC_COMBOBOX_DATA_LEN           106
#define IDD_DIALOG_EMAIL                106
#define IDC_COMBOBOX_PARITY             107
#define IDD_DIALOG_USER                 107
#define IDC_COMBOBOX_BITSTOP            108
#define IDD_DIALOG_LOG                  108
#define IDC_BUTTON_DEFAULT              109
#define IDD_DIALOG_SITE                 109
#define IDC_STATICFRAME_PARAM           110
#define IDC_BUTTONOPEN_COM              111
#define IDC_STATICTEXT_COM_PORT         111
#define IDC_COMBOBOX_COM_PORT           112
#define IDC_BUTTON_TIMING               113
#define IDC_BUTTON_SETUP                114
#define IDC_BUTTON_BACKUP               115
#define IDC_BUTTON_LAN                  116
#define IDC_BUTTON_EMAIL                117
#define IDC_BUTTON_LOG                  118
#define IDC_BUTTON_USERS                119
#define IDC_BUTTON_BACKUP_SITE          120
#define IDC_STATICTEXT_BITSTOP2         128
#define IDC_COMBOBOX_DTR_DSR            129
#define IDC_STATICTEXT_BITSTOP3         130
#define IDC_COMBOBOX_RTS_CTS            131
#define IDC_STATICTEXT_BITSTOP4         132
#define IDC_COMBOBOX_XON_XOFF           133
#define IDC_PROGRESSBAR_COMM            135
#define IDC_STATICTEXT_PROGRESS         136
#define IDC_BUTTON_ABORT_COMM           137
#define IDC_EDIT_HEADER                 217
#define IDC_EDIT_PORT                   217
#define IDC_EDIT_CODE                   218
#define IDC_IPADDRESS                   218
#define IDC_EDIT_VER                    219
#define IDC_IPADDRESS_DNS               219
#define IDC_IPADDRESS_GATEWAY           220
#define IDC_EDIT_PING                   221
#define IDC_EDIT_PING_64                222
#define IDC_EDIT_DELAY                  222
#define IDC_EDIT_PACKET                 223
#define ID_RADIO_BACKUP                 223
#define IDC_EDIT_SSID                   223
#define ID_RADIO_RESTORE                224
#define IDC_EDIT_PING3                  224
#define IDC_EDIT_WIFI_PSW               224
#define IDC_EDIT_PSW                    225
#define IDC_EDIT_FILE                   226
#define IDC_BUTTON_SEARCH               227
#define IDC_BUTTON_CURR_TIME            228
#define IDC_EDIT_CURR_TIME              229
#define IDC_BUTTON_SYNC_TIME            230
#define IDC_EDIT_AL_TIME_1              231
#define IDC_EDIT_AL_TIME_2              232
#define IDC_EDIT_SMTP                   232
#define IDC_EDIT_AL_TIME_3              233
#define IDC_EDIT_EMAIL_PORT             233
#define IDC_EDIT_AL_TIME_4              234
#define IDC_EDIT_EMAIL_FROM             234
#define IDC_EDIT_ENDRUN_TIME            235
#define IDC_EDIT_EMAIL_TO               235
#define IDC_LIST2                       235
#define IDC_EDIT_EMAIL_USER             236
#define IDC_LIST_USER                   236
#define IDC_EDIT_EMAIL_USER_64          237
#define IDC_EDIT_REC                    237
#define IDC_EDIT_EMAIL_PSW              238
#define IDC_RADIO_EMAIL                 238
#define IDC_EDIT_EMAIL_PSW_64           239
#define IDC_RADIO_ACCESS                239
#define IDC_LIST_FILES                  239
#define IDC_RADIO_ALARM                 240
#define IDC_EDIT_UPLOAD                 240
#define IDC_BUTTON_UPLOAD_FILE          241
#define IDC_EDIT_DOWNLOAD               242
#define IDC_CHECK_WIFI                  242
#define IDC_BUTTON_DOWNLOAD_PATH        243
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         243
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
