//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da maker.rc
//
#define IDB_BKG                         1
#define LOGO_IMAGE                      1
#define RCDATA_1                        1
#define IDI_ICON1                       1
#define IDB_TOOLBAR                     2
#define IDB_TOOLBAR_ACTION              3
#define IDI_ICON_TREND                  3
#define IDC_UNIQUE_TEXT                 3
#define IDC_BUTTON_AS_REM               3
#define IDB_CHOOSE_SEND_VAR             3
#define ID_BTN_PERSONALIZE_BORDER       3
#define IDB_TOOLBAR_PROJECT             4
#define IDC_BUTTON_AS_ADD               4
#define IDI_ICON_PROP                   5
#define IDB_TOOLBAR_640                 5
#define IDB_TOOLBAR_ACTION_640          6
#define IDI_ICON_RCP_FILE               6
#define IDB_TOOLBAR_PROJECT_640         7
#define IDI_ICON_MAINT                  7
#define IDB_BITMAP_CANC                 8
#define IDB_BITMAP_OK                   9
#define IDI_ICON_FLAG                   9
#define IDB_TOOLBAR_CHG_PAGE            10
#define IDI_ICON_STR                    10
#define IDI_ICON_PRINT                  11
#define IDB_TOOLBAR_CHG_PAGE_640        11
#define IDD_DIALOG_FILL_ASSOC_FILE      11
#define IDI_ICON_ALARM                  12
#define IDB_SAVE                        12
#define IDD_DIALOG_OPEN_ASSOC_FILE      12
#define IDI_ICON_PRINT2                 13
#define IDD_DIALOG_FILL_ALARM           13
#define IDB_FILL                        13
#define IDD_DIALOG_FILL_ASSOC           14
#define IDB_CLEAR                       14
#define IDB_DONE                        15
#define IDD_DIALOG_SHOW_TYPE            15
#define IDB_OPEN                        16
#define IDD_DIALOG_CLEAR                16
#define IDB_BAR                         17
#define IDD_DIALOG_SHOW_ASSOC_TYPE      17
#define IDD_CL_ASSOC_FILE               18
#define ID_BMP_SPIN                     18
#define IDD_DIALOG_ACTION               19
#define IDD_EDIT_GLOBAL_PAGE_TEXT       20
#define IDB_CHECK_ADDR                  21
#define IDC_TAB1                        100
#define IDD_MAIN_DIALOG                 100
#define IDC_STATIC_ACTION               100
#define IDC_SKIP_ACTION                 101
#define ID_OK                           101
#define IDC_EDIT_FILL_AL_START          101
#define IDC_EDIT_FILL_AS_START          101
#define IDC_CHECK_TYPE1                 101
#define IDC_CHECK_CLEAR_ALL             101
#define IDC_BUTTON_ADD_TAB              101
#define IDC_CHECKBOX_ENABLE_FG          101
#define IDC_GROUPBOX15                  101
#define IDC_GROUPBOX_1                  101
#define IDC_LISTBOX_BMP                 101
#define IDC_LISTBOX_FONT_ALLOCATED      101
#define IDC_LISTBOX_PAGEFILES           101
#define IDC_LISTBOX_VAR_TEXT            101
#define IDC_RADIOBUTTON_NO_BKG_PANEL    101
#define IDC_RADIOBUTTON_SIMPLE_TEXT     101
#define IDC_STATICFRAME22               101
#define IDC_TABCONTROL1                 101
#define IDD_DIALOG_CHOOSE_PATH          101
#define IDR_ACCELERATOR1                101
#define IDC_SKIP_ALL_ACTION             102
#define IDC_EDIT_FILL_AL_LEN            102
#define IDC_EDIT_FILL_AS_LEN            102
#define IDC_CHECK_TYPE2                 102
#define IDC_EDIT_CLEAR_FROM             102
#define IDC_BUTTON_REM_TAB              102
#define IDC_BUTTON_ADD_BMP              102
#define IDC_BUTTON_ADD_FONT             102
#define IDC_CHECKBOX_ENABLE_BG          102
#define IDC_EDIT_PAGE_TITLE             102
#define IDC_EDIT_VAR_TEXT               102
#define IDC_GROUPBOX5                   102
#define IDC_GROUPBOX_2                  102
#define IDC_RADIOBUTTON_CHOOSE_NAME     102
#define IDC_RADIOBUTTON_VAR_TEXT        102
#define IDC_RB_ACTION_EXPORT_CURR       102
#define IDC_STATICFRAME24               102
#define IDC_STATICTEXT_NETWORK          102
#define IDC_STATIC_PIVOT                102
#define IDD_TEXT_PROPERTY               102
#define IDC_GROUPBOX22                  102
#define ID_OK2                          102
#define IDC_APPLY_ACTION                103
#define IDC_CHECKBOX_FILL_AL_GRP        103
#define IDC_CHECKBOX_FILL_AS_PRPH       103
#define IDC_CHECK_TYPE3                 103
#define IDC_EDIT_CLEAR_TO               103
#define IDC_BUTTON_TOGGLE_VIS           103
#define IDC_BUTTON_ADD_VAR_TEXT         103
#define IDC_BUTTON_CHOOSE_BMP           103
#define IDC_BUTTON_MOD_FONT             103
#define IDC_BUTTON_UP_BMP               103
#define IDC_CHECKBOX_ENABLE_PRF         103
#define IDC_COMBOBOX_PRF_2              103
#define IDC_EDIT_STD_NETWORK            103
#define IDC_RADIOBUTTON_CHOOSE_ID       103
#define IDC_RB_ACTION_EXPORT_HIST       103
#define IDC_SCROLLBAR_COUNT             103
#define IDC_STATICFRAME4                103
#define IDC_STATIC_AXES                 103
#define IDD_CHOOSE_FONT                 103
#define IDC_GROUPBOX24                  103
#define IDC_APPLY_ALL_ACTION            104
#define IDC_EDIT_FILL_AL_GRP            104
#define IDC_EDIT_FILL_AS_PRPH           104
#define IDC_CHECK_TYPE4                 104
#define IDC_BUTTON_FIND_NETWORK         104
#define IDC_BUTTON_MOD_VAR_TEXT         104
#define IDC_BUTTON_REM_BMP              104
#define IDC_BUTTON_REM_FONT             104
#define IDC_CHECKBOX_HIDE_HEADER        104
#define IDC_EDIT_CHOOSE_NAME            104
#define IDC_EDIT_WARN_HOUR              104
#define IDC_GROUPBOX2                   104
#define IDC_GROUPBOX_PERIF              104
#define IDD_COMMON_PROPERTY             104
#define IDC_COMBOBOX_PRF_6              104
#define IDC_CHECKBOX_FILL_AL_FILTER     105
#define IDC_CHECKBOX_FILL_AS_ADDR       105
#define IDC_CHECK_TYPE5                 105
#define IDC_BUTTON_DEL_VAR_TEXT         105
#define IDC_BUTTON_DN_BMP               105
#define IDC_CHECKBOX_HIDE_FOOTER        105
#define IDC_COMBOBOX_CHOOSE_PERIF       105
#define IDC_COMBOBOX_CHOOSE_PREDEF      105
#define IDC_COMBOBOX_PRF_3              105
#define IDC_EDIT_ALERT_HOUR             105
#define IDC_EDIT_RESULT_NORM            105
#define IDC_STATICTEXT_PERIF            105
#define IDD_TEXT_AND_COLOR              105
#define IDC_BUTTON_UPD_FONT             105
#define IDC_GROUPBOX28                  105
#define IDC_BUTTON_CHOOSE_MONITOR       105
#define IDC_EDIT_FILL_AL_FILTER         106
#define IDC_EDIT_FILL_AS_ADDR           106
#define IDC_CHECK_TYPE6                 106
#define IDC_BUTTON_CHOOSE_NAME          106
#define IDC_BUTTON_UP_VAR_TEXT          106
#define IDC_CHECKBOX_LOCAL_PAGE         106
#define IDC_COMBOBOX_PERIFS             106
#define IDC_STATICFRAME14               106
#define IDD_NORMALZ                     106
#define IDC_COMBOBOX_PRF_7              106
#define IDC_EDIT_STD_BIT_SS_OFFS        106
#define IDC_CHECKBOX_FILL_AL_TEXT       107
#define IDC_CHECKBOX_FILL_AS_TYPE       107
#define IDC_CHECK_TYPE7                 107
#define IDC_BUTTON_DOWN_VAR_TEXT        107
#define IDC_COMBOBOX_PRF_4              107
#define IDC_COMBOBOX_TYPEVAL            107
#define IDC_STATICFRAME15               107
#define IDD_PAGE_PROPERTY               107
#define IDC_RADIOBUTTON_P_STANDARD      107
#define IDC_GROUPBOX29                  107
#define IDC_EDIT_FILL_AL_TEXT           108
#define IDC_COMBOBOX_FILL_AS_TYPE       108
#define IDC_CHECK_TYPE8                 108
#define IDC_BUTTON_FG_NORM_LB           108
#define IDC_BUTTON_FG_VAR_TEXT          108
#define IDC_COMBOBOX_ACTION_F1          108
#define IDC_STATICTEXT_ADDR             108
#define IDC_STATICTEXT_APPL_TIMER       108
#define IDD_ACTION_OPEN_PAGE            108
#define IDC_RADIOBUTTON_P_RECIPE        108
#define IDC_COMBOBOX_PRF_8              108
#define IDC_EDIT_STD_M_TIT_PRESET       108
#define IDC_COMBOBOX_PERIFS_FLT         108
#define IDC_COMBOBOX_GRID_TYPE          108
#define IDC_CHECKBOX_ENABLE_PRF_V       108
#define IDC_GROUPBOX35                  108
#define IDC_CHECKBOX_FILL_AS_NBIT       109
#define IDC_CHECK_TYPE9                 109
#define IDC_BUTTON_BG_NORM_LB           109
#define IDC_BUTTON_BG_VAR_TEXT          109
#define IDC_COMBOBOX_ACTION_F2          109
#define IDC_COMBOBOX_PRF_5              109
#define IDC_EDIT_ADDR                   109
#define IDC_EDIT_APPL_TIMER             109
#define IDC_EDIT_NAME_BMP               109
#define IDD_ACTION_OPEN_NAME            109
#define IDC_RADIOBUTTON__P_RECIPE_LB    109
#define IDC_EDIT_STD_M_HOUR_PRESET      109
#define IDC_EDIT_FILL_AS_NBIT           110
#define IDC_CHECK_TYPE10                110
#define IDC_CHECKBOX_NO_COLORS          110
#define IDC_COMBOBOX_ACTION_F3          110
#define IDC_GROUPBOX13                  110
#define IDC_STATICTEXT_TYPE             110
#define IDD_ACTION_OPEN_PERIF           110
#define IDC_RADIOBUTTON_P_RECIPE_ROW    110
#define IDC_EDIT_STD_M_MINUTE_PRESET    110
#define IDC_EDIT_ADDR_FLT               110
#define IDC_GROUPBOX36                  110
#define IDC_COMBOBOX_TRAY_DATATYPE      110
#define IDC_STATICTEXT_APPL_TIMER2      110
#define IDC_CHECKBOX_FILL_AS_OFFS       111
#define IDC_CHECK_TYPE11                111
#define IDC_BUTTON_FG_SELECT_LB         111
#define IDC_COMBOBOX_ACTION_F4          111
#define IDC_COMBOBOX_PERIFS_MIN_Y       111
#define IDC_GROUPBOX1                   111
#define IDC_RADIOBUTTON_LINE_STOP       111
#define IDC_STATICTEXT_EXP_SEP          111
#define IDC_STATICTEXT_VALUE_COLOR      111
#define IDC_STATICTEX_NBITS             111
#define IDD_ACTION_OPEN_ID              111
#define IDC_EDIT_STD_M_TIT_WARN         111
#define IDC_GROUPBOX30                  111
#define IDC_GROUPBOX37                  111
#define IDC_COMBOBOX_TRAY_LEVEL         111
#define IDC_EDIT_FILL_AS_OFFS           112
#define IDC_CHECK_TYPE12                112
#define IDC_BUTTON_BG_SELECT_LB         112
#define IDC_COMBOBOX_ACTION_F5          112
#define IDC_COMBOBOX_EXP_SEP            112
#define IDC_EDIT_NBITS                  112
#define IDC_EDIT_VAR_TEXT_VALUE         112
#define IDC_RADIOBUTTON_LINE_RUN        112
#define IDD_ACTION_EXPORT               112
#define IDC_RADIOBUTTON_P_GRAPH_TREND   112
#define IDC_EDIT_STD_M_TIT_RESET        112
#define IDC_COMBOBOX_PSW_LEVEL          112
#define IDC_STATICFRAME28               112
#define IDC_GROUPBOX42                  112
#define IDC_CHECK_TYPE13                113
#define IDC_COMBOBOX_ACTION_F6          113
#define IDC_EDIT_ADDR_MIN_Y             113
#define IDC_RADIOBUTTON_LINE_BITS       113
#define IDC_STATICTEXT_OFFSET           113
#define IDD_DIALOG_OPEN_PAGE            113
#define IDC_RADIOBUTTON_P_GRAPH_MAINT   113
#define IDC_EDIT_APPL_TIMER2            113
#define IDC_COMBOBOX_PING_TYPE          113
#define IDC_COMBOBOX_TYPEVAL7           113
#define IDC_CHECKBOX_FILL_AS_ASSOC_TYPE 113
#define IDC_BUTTON_MODIFY_VAR_TEXT      113
#define IDC_COMBOBOX_PERIFS_FLT_TXT     113
#define IDC_CHECK_TYPE14                114
#define IDC_COMBOBOX_ACTION_F7          114
#define IDC_EDIT_OFFSET                 114
#define IDC_RADIOBUTTON_LINE_VALUE      114
#define IDC_STATICTEXT_DEC_SEP          114
#define IDD_DIALOG_SAVE_PAGE            114
#define IDC_EDIT_STD_M_MSG_RESET        114
#define IDC_EDIT_NBITS2                 114
#define IDC_EDIT_FILL_AS_ASSOC_FILE     114
#define IDC_EDIT_ADDR_FLT_TXT           114
#define IDC_BUTTON_COPY_TO_CLIP         114
#define IDC_CHECK_TYPE15                115
#define IDC_CHECKBOX_NEGATIVE           115
#define IDC_CHECKBOX_REVERSE_Y          115
#define IDC_COMBOBOX_ACTION_F8          115
#define IDC_COMBOBOX_DEC_SEP            115
#define IDC_STATIC_BKG                  115
#define IDD_BMP_PROPERTY                115
#define IDC_COMBOBOX_PRF_9              115
#define IDC_EDIT_FILL_AS_ADDR_STEP      115
#define IDC_EDIT_OFFSET2                115
#define IDC_BUTTON_PASTE_FROM_CLIP      115
#define IDC_BUTTON_ADD_COLOR            116
#define IDC_COMBOBOX_ACTION_F9          116
#define IDC_COMBOBOX_TYPEVAL_MIN_Y      116
#define IDC_GROUPBOX18                  116
#define IDC_STATICFRAME23               116
#define IDC_STATICTEXT_FOREGROUND       116
#define IDD_CHOOSE_BMP                  116
#define IDC_STATICTEXT_REFRESH_ALARM    116
#define IDC_EDIT_NORM                   116
#define IDC_EDIT_PRPH_FROM              116
#define IDC_COMBOBOX_FILL_AS_ASSOC_TYPE 116
#define IDC_GROUPBOX9                   116
#define IDC_BUTTON_REM_COLOR            117
#define IDC_COMBOBOX_ACTION_F10         117
#define IDC_STATICTEXT_BACKGROUND       117
#define IDC_STATICTEXT_HIDE_PART        117
#define IDD_BMP_MOVIM                   117
#define IDC_EDIT_PRPH_TO                117
#define IDC_CHECKBOX_FILL_AS_ASSOC_FILE 117
#define IDC_EDIT_CHOOSE_FILE_FIX        117
#define IDC_BUTTON_CHOOSE_FG            118
#define IDC_COMBOBOX_ACTION_F11         118
#define IDC_COMBOBOX_HIDE_PART          118
#define IDC_EDIT_NORM_MIN_Y             118
#define IDD_SIMPLE_BMP_PROPERTY         118
#define IDC_EDIT_SIMPLE_TXT             118
#define IDC_BUTTON_CHOOSE_BG            119
#define IDC_BUTTON_NORMALIZ_MIN_Y       119
#define IDC_COMBOBOX_ACTION_F12         119
#define IDD_PANEL_PROPERTY              119
#define IDC_COMBOBOX_REFRESH_ALARM      119
#define IDC_EDIT_PRPH_FROM2             119
#define IDC_BUTTON_FG_PRESS             120
#define IDC_BUTTON_UP_COLOR             120
#define IDC_CHECKBOX_AUTO_UPDATE_EDIT   120
#define IDC_CHECKBOX_HIDE_TIME          120
#define IDC_GROUPBOX6                   120
#define IDD_EDIT_PROPERTY               120
#define IDC_EDIT_PRPH_TO2               120
#define IDC_BUTTON_DN_COLOR             121
#define IDC_CHECKBOX_SHOW_ON_SENDING    121
#define IDC_STATICTEXT_FONT             121
#define IDC_STD_LABEL_1                 121
#define IDD_BTN_PROPERTY                121
#define IDC_EDIT_ADDR_FROM              121
#define IDC_BUTTON_CHOOSE_FONT          122
#define IDC_COMBOBOX_PERIFS_MAX_X       122
#define IDC_STATICTEXT_EDIT_RESET       122
#define IDC_STD_LABEL_2                 122
#define IDD_BARGRAPH_PROPERTY           122
#define IDC_EDIT_ADDR_TO                122
#define IDC_CHECKBOX_ENABLE_ADDR        123
#define IDC_EDIT_COMMAND                123
#define IDC_EDIT_TIME_RESET_EDIT        123
#define IDC_GROUPBOX19                  123
#define IDC_GROUPBOX_CENTER             123
#define IDC_STATIC_CROWN                123
#define IDC_STD_LABEL_3                 123
#define IDD_LED_PROPERTY                123
#define IDC_EDIT_ADDR_STAT_LINE         123
#define IDC_BUTTON_CHOOSE_TEXT_COLOR    123
#define IDC_CHECKBOX_ENABLE_VALUETYPE   124
#define IDC_EDIT_ADDR_MAX_X             124
#define IDC_EDIT_BKG_FILENAME           124
#define IDC_EDIT_LEN_EDIT               124
#define IDC_EDIT_SIMPLE_TEXT            124
#define IDC_EDIT_FIX_FILTER             124
#define IDC_RADIOBUTTON__640x480        124
#define IDC_STD_LABEL_4                 124
#define IDD_LISTBOX_PROPERTY            124
#define IDC_BUTTON_CHOOSE_BKG           125
#define IDC_RADIOBUTTON__800x600        125
#define IDC_STATICFRAME5                125
#define IDC_STD_LABEL_5                 125
#define IDD_DIAM_PROPERTY               125
#define IDC_SCROLLBAR_STD_M             125
#define IDC_SCROLLBAR_CC                125
#define IDC_SCROLLBAR_GR_R              125
#define IDC_EDIT_FIXED_FILE             125
#define IDC_EDIT_FIX_FILTER2            125
#define IDC_EDIT_ADDR_FLT_TXT_LEN       125
#define IDC_COMBOBOX_TYPEVAL_MAX_X      126
#define IDC_GROUPBOX3                   126
#define IDC_RADIOBUTTON_TILED           126
#define IDC_RADIOBUTTON__1024x768       126
#define IDC_STD_LABEL_6                 126
#define IDD_DIAM_CHOOSE_COLOR           126
#define IDC_SCROLLBAR_GR_G              126
#define IDC_CHECKBOX_READ_ONLY          127
#define IDC_RADIOBUTTON_ALTERNATE       127
#define IDC_RADIOBUTTON_CENTERED        127
#define IDC_RADIOBUTTON_STYLE_NONE      127
#define IDC_RADIOBUTTON__1280x1024      127
#define IDC_STD_LABEL_7                 127
#define IDD_CHOOSE_PROPERTY             127
#define IDC_SCROLLBAR_GR_B              127
#define IDC_EDIT_NORM_MAX_X             128
#define IDC_RADIOBUTTON_SCALED          128
#define IDC_RADIOBUTTON_SHOW_HIDE       128
#define IDC_RADIOBUTTON_SIMPLE_BORDER   128
#define IDC_STD_LABEL_8                 128
#define IDD_CHOOSE_TEXT                 128
#define IDC_RADIOBUTTON__1440x900       128
#define IDC_BUTTON_NORMALIZ_MAX_X       129
#define IDC_CHECKBOX_HIDE_ALARM_TYPE    129
#define IDC_RADIOBUTTON_FILLED          129
#define IDC_RADIOBUTTON_UP_BORDER       129
#define IDC_STD_LABEL_9                 129
#define IDD_DIALOG_DEFAULT_STD          129
#define IDC_RADIOBUTTON__1600x1200      129
#define IDD_DIALOG_DEFAULT_GRAPH        130
#define IDC_GROUPBOX4                   130
#define IDC_RADIOBUTTON_DOWN_BORDER     130
#define IDC_STD_LABEL_10                130
#define IDC_CHECKBOX_PREDEF_F1          130
#define IDC_RADIOBUTTON__1680x1050      130
#define IDC_CHECKBOX_FILL_PANEL         131
#define IDC_EDIT_LINE_V1                131
#define IDC_RADIOBUTTON_FILL_PANEL      131
#define IDC_STD_LABEL_11                131
#define IDC_GROUPBOX20                  131
#define IDD_DIALOG_GR_CHG_TEXT          131
#define IDC_CHECKBOX_ORD_ALARM          131
#define IDC_RADIOBUTTON__1920x1440      131
#define IDC_CHECKBOX_REVERSE_X          132
#define IDC_CHECKBOX_TRANSP_PANEL       132
#define IDC_EDIT_LINE_V5                132
#define IDC_STATICFRAME16               132
#define IDC_STATICTEXT_DATE_FORM        132
#define IDC_STD_LABEL_12                132
#define IDD_WZ_RECIPE                   132
#define IDC_GROUPBOX34                  132
#define IDC_RADIOBUTTON__RES_PERS       132
#define IDC_BUTTON_CHOOSE_PIVOT         133
#define IDC_CHECKBOX_ENABLE_NBITS       133
#define IDC_COMBOBOX_DATE_TYPE          133
#define IDC_COMBOBOX_PERIFS_MAX_Y       133
#define IDC_EDIT_LINE_V2                133
#define IDC_RADIOBUTTON_VAR_VALUE       133
#define IDC_STD_LABEL_13                133
#define IDC_EDIT_LINKED_PAGE            133
#define IDD_WZ_FIRST_PAGE               133
#define IDC_RADIOBUTTON_STYLE_NONE2     133
#define IDC_GROUPBOX41                  133
#define IDC_BUTTON_MOVIM                134
#define IDC_EDIT_LINE_V6                134
#define IDC_STD_LABEL_14                134
#define IDC_BUTTON_CHOOSE_LINKED_PAGE   134
#define IDC_CHECKBOX_PREDEF_F12         134
#define IDD_WZ_TREND                    134
#define IDC_RADIOBUTTON_SIMPLE_BORDER2  134
#define IDC_EDIT_LINE_V3                135
#define IDC_EDIT_SCALE_X                135
#define IDC_STATICFRAME6                135
#define IDC_STATICTEXT_FONT_HEIGHT      135
#define IDD_WZ_RECIPE_ROW               135
#define IDC_STD_LABEL_15                135
#define IDC_CHECKBOX_ENABLE_ADDR_V      135
#define IDC_RADIOBUTTON_UP_BORDER2      135
#define IDC_CHECKBOX_ENABLE_ALIGN       136
#define IDC_EDIT_FONT_HEIGHT            136
#define IDC_EDIT_LINE_V7                136
#define IDC_EDIT_SCALE_Y                136
#define IDC_STD_LABEL_16                136
#define IDD_CURVE_PROPERTY              136
#define IDC_RADIOBUTTON_DOWN_BORDER2    136
#define IDC_STATICFRAME31               136
#define IDC_CHECKBOX_TRANSPARENT        137
#define IDC_EDIT_ADDR_MAX_Y             137
#define IDC_EDIT_LINE_V4                137
#define IDC_RADIOBUTTON_A_LEFT          137
#define IDD_XMETER_PROPERTY             137
#define IDC_STATICTEXT_RESOLUTION       137
#define IDC_CHECKBOX_FILL_PANEL3        137
#define IDC_BUTTON_DLG_ACTION_F1        138
#define IDC_EDIT_LINE_V8                138
#define IDC_RADIOBUTTON_A_RIGHT         138
#define IDC_STATICTEXT_FONT_NAME        138
#define IDD_CAM_PROPERTY                138
#define IDC_GROUPBOX39                  138
#define IDD_ACTION_ONLY_PSW             139
#define IDC_BUTTON_DLG_ACTION_F2        139
#define IDC_COMBOBOX_TYPEVAL_MAX_Y      139
#define IDC_EDIT_FONT_NAME              139
#define IDC_GROUPBOX16                  139
#define IDC_RADIOBUTTON_A_CENTER        139
#define IDC_EDIT_KEYB_ALPHA             139
#define IDC_GROUPBOX40                  139
#define IDD_ACTION_PRINT_SCREEN         140
#define IDC_CHECKBOX_PREVIEW            140
#define IDC_BUTTON_DLG_ACTION_F3        140
#define IDC_EDIT_X                      140
#define IDC_COMBOBOX_RESOLUTION         140
#define IDC_EDIT_LOCAL_DWORD            140
#define IDD_DIALOG_DEFAULT_RECIPE       141
#define IDC_CHECKBOX_SETUP              141
#define IDC_BUTTON_DLG_ACTION_F4        141
#define IDC_EDIT_Y                      141
#define IDC_STATICTEXT_FONT_WIDTH       141
#define IDC_GROUPBOX21                  141
#define IDC_EDIT_KEYB_NUMB              141
#define IDC_BUTTON_DLG_ACTION_F5        142
#define IDC_EDIT_FONT_WIDTH             142
#define IDC_EDIT_W                      142
#define IDD_WZ_MAIN                     142
#define IDC_EDIT_WARNING_LEVEL          142
#define IDC_CHECKBOX_SHOW_ALARM_INACTIVE 143
#define IDC_BUTTON_DLG_ACTION_F6        143
#define IDC_EDIT_H                      143
#define IDD_OFFSCREEN                   143
#define IDD_XSCOPE_PROPERTY             144
#define IDC_BUTTON_DLG_ACTION_F7        144
#define IDC_CHECKBOX_ENABLE_NEGATIVE    144
#define IDC_GROUPBOX17                  144
#define IDC_CHECKBOX_NOQUEUE_PAGE       144
#define IDC_RADIOBUTTON_BASE_10         144
#define IDC_BUTTON_DLG_ACTION_F8        145
#define IDC_CHECKBOX_ENABLE_BORDER      145
#define IDC_STATICTEXT_MASK             145
#define IDC_EDIT_ALARM_FILTER           145
#define IDC_STATICTEXT_TIMEOUT_SEND_REC 145
#define IDC_GROUPBOX23                  145
#define IDD_EDIT_ASSOC                  145
#define IDC_RADIOBUTTON_BASE_2          145
#define IDD_TREND_PROPERTY              146
#define IDC_BUTTON_DLG_ACTION_F9        146
#define IDC_CHECKBOX_ENABLE_X           146
#define IDC_EDIT_NORM_MAX_Y             146
#define IDC_STATICFRAME17               146
#define IDC_STATICTEXT_BULLET           146
#define IDC_EDIT_TIMEOUT_SEND_REC       146
#define IDC_GROUPBOX33                  146
#define IDC_RADIOBUTTON_BASE_16         146
#define IDD_TREND_CHOOSE_COLOR          147
#define IDC_BUTTON_CHOOSE_AXIS          147
#define IDC_BUTTON_DLG_ACTION_F10       147
#define IDC_BUTTON_NORMALIZ_MAX_Y       147
#define IDC_CHECKBOX_ENABLE_Y           147
#define IDC_COMBOBOX_PERIFS_2           147
#define IDC_EDIT_MEM_ADDR               147
#define IDC_STATICTEXT_GRID             147
#define IDC_STATICTEXT_DELAY_DRIVER     147
#define IDD_CHOOSE_TREND_NAME           148
#define IDC_BUTTON_COLOR_BULLET         148
#define IDC_BUTTON_DLG_ACTION_F11       148
#define IDC_CHECKBOX_ENABLE_W           148
#define IDC_COMBOBOX_FLAG_TYPE          148
#define IDC_EDIT_ADDR_2                 148
#define IDC_EDIT_MEM_VALUE              148
#define IDC_GROUPBOX11                  148
#define IDC_STATICFRAME20               148
#define IDC_EDIT_DELAY_DRIVER           148
#define IDD_SPIN_PROPERTY               149
#define IDC_BUTTON_COLOR_GRID           149
#define IDC_BUTTON_DLG_ACTION_F12       149
#define IDC_CHECKBOX_ENABLE_H           149
#define IDC_COMBOBOX_TYPEVAL_2          149
#define IDC_LISTBOX_MEM_VARS            149
#define IDC_STATICFRAME18               149
#define IDC_CHECKBOX_EXT_KEYB           149
#define IDC_EDIT_TRAY_OFFS              149
#define IDD_ALARM_EDITOR                150
#define IDC_BUTTON_ADD_MEM_VAR          150
#define IDC_CHECKBOX_ENABLE_FONT        150
#define IDC_CHECKBOX_PP_MOD_PAGE        150
#define IDC_COMBOBOX_PERIFS2            150
#define IDC_EDIT_NORMALIZ_2             150
#define IDC_GROUPBOX7                   150
#define IDC_STATICFRAME19               150
#define IDC_STATICTEXT_AXE              150
#define IDC_CHECK_BTN_FZ_TEXT           150
#define IDC_EDIT_PSW_TIME               150
#define IDD_CL_ALARM                    151
#define IDC_BUTTON_COLOR_AXE            151
#define IDC_BUTTON_REM_MEM_VAR          151
#define IDC_CHECKBOX_PP_MODELESS        151
#define IDC_EDIT_NBITS_2                151
#define IDC_STATICFRAME7                151
#define IDC_CHECK_BTN_FZ_TEXT_PRFX      151
#define IDC_EDIT_PING_BIT               151
#define IDD_CL_ASSOC                    152
#define IDC_BUTTON_NORMALIZ_CURR_Y      152
#define IDC_EDIT_ADDR2                  152
#define IDC_EDIT_OFFSET_2               152
#define IDC_STATICFRAME8                152
#define IDC_EDIT_DLL                    152
#define IDC_BUTTON_PREV_PAGE            152
#define IDC_CHECK_BTN_FZ_DISABLE        152
#define IDD_ACTION_SPIN                 153
#define IDC_BUTTON_SAVE_ALARM           153
#define IDC_EDIT_MODAL_X                153
#define IDC_EDIT_PERC1ST                153
#define IDC_RADIOBUTTON_NO_ERASE_BKG    153
#define IDC_STATICFRAME9                153
#define IDC_BUTTON_ADD_DLL              153
#define IDC_STATICTEXT_CURR_DATETIME    153
#define IDC_BUTTON_SAVE_AS              154
#define IDC_BUTTON_NORMALIZ_2           154
#define IDC_COMBOBOX_TYPEVAL2           154
#define IDC_EDIT_NORM_CURR_Y            154
#define IDC_STATICFRAME10               154
#define IDC_EDIT_LINKED_PAGE_X          154
#define IDC_BUTTON_REM_DLL              154
#define IDC_EDIT_CURR_DATETIME          154
#define IDD_STD_MSG_CHOOSE_MONITOR      154
#define IDC_BUTTON_FILL                 155
#define IDC_COMBOBOX_TYPEVAL_CURR_Y     155
#define IDC_EDIT_MODAL_W                155
#define IDC_EDIT_POINT1ST               155
#define IDC_GROUPBOX10                  155
#define IDC_STATICFRAME11               155
#define IDC_LISTBOX_DLL                 155
#define IDC_STATICTEXT_PSW_CHAR         155
#define IDD_AD4                         155
#define IDD_TABLE_INFO_PROPERTY         156
#define IDC_BUTTON_CLEAR                156
#define IDC_CHECKBOX_ENABLE_NORMALIZ    156
#define IDC_BUTTON_NEXT_PAGE            156
#define IDC_EDIT_PSW_CHAR               156
#define IDC_EDIT_PAG_CHOOSE_H_FONT      156
#define IDC_EDIT_TRAY_TIPS              156
#define IDC_CHECKBOX_ENABLE_OFFSET      157
#define IDC_CLOSE_ALARM                 157
#define IDC_EDIT_MODAL_Y                157
#define IDC_CHECKBOX_DATA_ALARM         157
#define IDC_BUTTON_PAG_FGN              157
#define IDC_EDIT_TRAY_TIPS_OK           157
#define IDD_TBL_INFO_HEAD               157
#define IDD_TBL_INFO_FIRST              158
#define IDC_BUTTON_GOTO_ROW             158
#define IDC_EDIT_ADDR_CURR_Y            158
#define IDC_EDIT_NORMALIZ               158
#define IDC_EDIT_LINKED_PAGE_Y          158
#define IDC_STATICTEXT_DELAY_AUTORUN    158
#define IDC_BUTTON_PAG_BGN              158
#define IDC_EDIT_TRAY_TIPS_HEAD         158
#define IDD_TBL_INFO_ROWS               159
#define IDC_EDIT_GOTO_ROW               159
#define IDC_EDIT_MODAL_H                159
#define IDC_STATICFRAME12               159
#define IDC_EDIT_DELAY_AUTORUN          159
#define IDC_BUTTON_PAG_FGS              159
#define IDD_GET_KEY_USER                160
#define IDC_STATIC_PRPH                 160
#define IDC_BUTTON_NORMALIZ             160
#define IDC_BUTTON_NORMALIZ_MIN_X       160
#define IDC_BUTTON_PAG_BGS              160
#define IDC_STATICTEXT_MONITOR          160
#define IDC_CHECKBOX_PP_NO_TITLE        160
#define IDC_BUTTON_EDIT_SECTION         160
#define IDC_STATIC_DESCR                161
#define IDC_COMBOBOX_PERIFS_CURR_Y      161
#define IDC_EDIT_NORMALIZ2              161
#define IDC_STATICFRAME13               161
#define IDC_EDIT_PAG_CHOOSE_FONT        161
#define IDC_EDIT_MONITOR                161
#define IDD_ADDR_OFFSET                 161
#define IDC_CHECKBOX_PP_TRANSP          161
#define IDD_WZ_LINKED_PAGE              162
#define IDC_EDIT_NDEC                   162
#define IDC_EDIT_NORM_MIN_X             162
#define IDC_EDIT_VAR1_RES_PERS_W        162
#define IDC_BUTTON_CHOOSE_FILE          162
#define IDC_BUTTON_CHOOSE_DLL           162
#define IDC_BUTTON_NORMALIZ2            163
#define IDC_GROUPBOX8                   163
#define IDC_TIMECYCLE                   163
#define IDC_EDIT_VAR1_RES_PERS_H        163
#define IDC_CURSOR_PAN                  163
#define IDD_XY_PLOT_PROPERTY            163
#define IDC_BUTTON_SEARCH_TEXT          163
#define IDC_CURSOR_PAN_MOVE             164
#define IDC_BUTTON_NORMALIZ_CURR_X      164
#define IDC_CHECKBOX_ENABLE_NDEC        164
#define IDC_GROUPBOX12                  164
#define IDD_BORDER_STYLE                164
#define IDC_CHECKBOX_HIDE_ALARM_PRPH    164
#define IDC_EDIT_SEARCH_TEXT            164
#define IDC_CHECKBOX_ENABLE_DX          165
#define IDC_EDIT_NORM_CURR_X            165
#define IDC_GROUPBOX25                  165
#define IDD_CHOOSE_PASTE_RCP_TYPE       165
#define IDC_CHECKBOX_HIDE_REPORT_PRPH   165
#define IDC_BUTTON_COPY2                165
#define IDC_CHECKBOX_ENABLE_DY          166
#define IDC_COMBOBOX_PERIFS3            166
#define IDD_MIRROR                      166
#define IDC_COMBOBOX_TYPEVAL_CURR_X     167
#define IDC_EDIT_DX                     167
#define IDC_COMBOBOX_PERIFS4            167
#define IDD_DIALOG_YES_NO_ALL           167
#define IDC_EDIT_ADDR3                  168
#define IDC_EDIT_DY                     168
#define IDD_DIALOG1                     168
#define IDD_DIALOG_CHECKADDR            168
#define IDC_EDIT_ADDR_CURR_X            169
#define IDC_EDIT_ADDR4                  169
#define IDB_COPY                        169
#define IDC_COMBOBOX_TYPEVAL3           170
#define IDC_CHECKBOX_ENABLE_NBITS_V     170
#define IDD_DIALOG_OPEN_SOURCE          170
#define IDC_COMBOBOX_PERIFS_CURR_X      171
#define IDC_COMBOBOX_TYPEVAL4           171
#define IDC_CHECKBOX_ENABLE_OFFSET_V    171
#define IDD_DIALOG2                     171
#define IDC_GROUPBOX26                  172
#define IDC_COMBOBOX_PERIFS5            173
#define IDC_STATICFRAME32               173
#define IDC_EDIT_ADDR5                  174
#define IDC_STATICFRAME33               174
#define IDC_EDIT_NORMALIZ3              175
#define IDC_BUTTON_NORMALIZ3            176
#define IDC_BUTTON_NORMALIZ4            177
#define IDC_EDIT_NORMALIZ4              178
#define IDC_STATICFRAME25               178
#define IDC_COMBOBOX_TYPEVAL5           179
#define IDC_STATICFRAME26               179
#define IDC_BUTTON_NORMALIZ5            180
#define IDC_STATICFRAME27               180
#define IDC_EDIT_NORMALIZ5              181
#define IDC_GROUPBOX27                  182
#define IDC_STATICFRAME29               182
#define IDC_COMBOBOX_PERIFS6            183
#define IDC_EDIT_ADDR6                  184
#define IDC_COMBOBOX_TYPEVAL6           185
#define IDC_STATICFRAME30               186
#define IDC_GROUPBOX43                  186
#define IDC_EDIT_NORMALIZ6              187
#define IDC_CHECKBOX_ENABLE_NEG_V       187
#define IDC_EDIT_ADDR_BITS_READY        188
#define IDC_EDIT_NUM_ROW_XSCOPE         189
#define IDC_COMBOBOX_PERIF_MIN_X        190
#define IDC_EDIT_ADDR_PXY_MIN_X         191
#define IDC_COMBOBOX_TYPEVAL_PXY_MIN_X  192
#define IDC_BUTTON_NORMALIZ_PXY_MIN_X   193
#define IDC_EDIT_NORMALIZ_PXY_MIN_X     194
#define IDC_GROUPBOX44                  195
#define IDC_COMBOBOX_PERIF_MAX_X        196
#define IDC_STATIC_MASK                 197
#define IDC_EDIT_ADDR_PXY_MAX_X         197
#define IDC_STATIC_ASS_ADDR             198
#define IDC_COMBOBOX_TYPEVAL_PXY_MAX_X  198
#define IDC_STATIC_ASS_TYPE             199
#define IDC_BUTTON_NORMALIZ_PXY_MAX_X   199
#define IDC_STATIC_ASS_NBIT             200
#define IDC_EDIT_NORMALIZ_PXY_MAX_X     200
#define IDC_STATIC_ASS_OFFS             201
#define IDC_EDIT_NUM_COL_XSCOPE         201
#define IDC_STATIC_ASS_BTN              202
#define IDC_GROUPBOX31                  203
#define IDC_GROUPBOX32                  204
#define IDC_COMBOBOX_PERIFS_MIN_X       205
#define IDC_COMBOBOX_TYPEVAL_MIN_X      206
#define IDC_COMBOBOX_PERIFS_MIN         207
#define IDC_EDIT_ADDR_MIN_X             208
#define IDC_EDIT_ADDR_MIN               209
#define IDB_TABS                        210
#define IDC_COMBOBOX_TYPEVAL_MIN        211
#define IDC_EDIT_NBITS_MIN              212
#define IDC_EDIT_NORMALIZ_MIN           213
#define IDC_BUTTON_NORMALIZ_MIN         214
#define IDC_EDIT_OFFSET_MIN             215
#define IDC_EDIT_TEXT_NORM              217
#define IDC_COMBOBOX_FLAG_TYPE_ACTION   218
#define IDC_GROUPBOX_9                  219
#define IDC_BUTTON_COPY                 220
#define IDC_GROUPBOX220                 220
#define IDC_BUTTON_BG_PRESS             221
#define IDC_BUTTON_BG_NORM              222
#define IDC_BUTTON_TEXT                 234
#define IDC_EDIT_X2                     242
#define IDC_EDIT_Y2                     243
#define IDC_BUTTON_TEXT_AND_COLOR       257
#define IDC_BUTTON_FG_NORM              258
#define IDC_BUTTON_COLORS               259
#define IDC_GROUPBOX_PT_ELAB            260
#define IDD_BUTTON_ADVANCED_TXT         295
#define IDD_BUTTON_ADVANCED_BMP         296
#define IDD_BUTTON_ADVANCED_COLOR       297
#define IDD_BUTTON_ADVANCED             298
#define IDD_STD_MSG_FLAG3               299
#define IDD_STD_MSG                     300
#define IDD_STD_MSG_TEXT                301
#define IDC_CHECKBOX_USE_COLORS         301
#define IDC_EDIT_DESCR_1                301
#define IDD_STD_MSG_FLAG1               302
#define IDC_EDIT_DESCR_2                302
#define IDD_STD_MSG_FLAG2               303
#define IDC_EDIT_DESCR_3                303
#define IDD_STD_MSG_ALARM               304
#define IDC_EDIT_DESCR_4                304
#define IDD_STD_MSG_MAINT               305
#define IDC_EDIT_DESCR_5                305
#define IDD_STD_MSG_CAUSE_STOP          306
#define IDC_EDIT_DESCR_6                306
#define IDD_STD_MSG_TREND               307
#define IDC_EDIT_DESCR_7                307
#define IDD_STD_MSG_PRINT_1             308
#define IDC_EDIT_DESCR_8                308
#define IDD_STD_MSG_PRINT_2             309
#define IDC_EDIT_DESCR_9                309
#define IDD_STD_MSG_LANG                310
#define IDC_EDIT_DESCR_10               310
#define IDD_EDIT_LANG                   311
#define IDC_CHECKBOX_DRAW_AXES          311
#define IDC_EDIT_DESCR_11               311
#define IDD_WZ_RECIPE_ROW_1             312
#define IDC_CHECKBOX_TRANSP_PIVOT       312
#define IDC_EDIT_DESCR_12               312
#define IDD_WZ_RECIPE_ROW_2             313
#define IDC_CHECKBOX_DRAW_MAX_DIAM      313
#define IDC_EDIT_DESCR_13               313
#define IDD_DIALOG_DEFAULT_RECIPEROW    314
#define IDC_CHECKBOX_REVERSE_DRAW       314
#define IDC_EDIT_DESCR_14               314
#define IDD_ALARM_PROPERTY              315
#define IDC_EDIT_DESCR_15               315
#define IDD_SEND_OPEN_CLOSE             316
#define IDC_EDIT_DESCR_16               316
#define IDD_STD_MSG_TREND_MOD           317
#define IDC_EDIT_TEXT_PRESSED           318
#define IDD_BUTTON                      319
#define IDD_SLIDER_PROPERTY             320
#define IDC_CHECKBOX_MOV                331
#define IDC_CHECKBOX_NEG_VALUE          333
#define IDC_GROUPBOX311                 334
#define IDC_EDIT_ALARM_INIT_2           401
#define IDC_EDIT_ALARM_NWORD_2          421
#define IDC_EDIT_ALARM_OFFS_EV_2        441
#define IDC_EDIT_ALARM_NWORD_EV_2       461
#define IDC_CHECK_USE_STATUS_FLAG_2     481
#define IDC_CHECK_USE_STATUS_FLAG_3     482
#define IDC_CHECK_USE_STATUS_FLAG_4     483
#define IDC_CHECK_USE_STATUS_FLAG_5     484
#define IDC_CHECK_USE_STATUS_FLAG_6     485
#define IDC_CHECK_USE_STATUS_FLAG_7     486
#define IDC_CHECK_USE_STATUS_FLAG_8     487
#define IDC_CHECK_USE_STATUS_FLAG_9     488
#define IDC_CHECK_USE_STATUS_FLAG_10    489
#define IDC_EDIT_ALARM_ADDR_STATUS_2    501
#define IDC_STATICTEXT_REAL_SIZE        516
#define IDC_EDIT_ALARM_BIT_MASK_2       521
#define IDC_COMBOBOX_SHOWTYPE           522
#define IDC_COMBOBOX_BTN_FZ_BEHA        523
#define IDC_EDIT_ALARM_BIT_MASK_EV_2    541
#define IDC_EDIT_ALARM_DATA_TYPE_2      561
#define IDC_EDIT_RESET_ADDR_2           581
#define IDC_EDIT_RESET_BIT_2            601
#define IDC_GROUPBOX38                  612
#define IDC_COMBOBOX_PERIFS_FLT_GRP     613
#define IDC_EDIT_ADDR_FLT_GRP           614
#define IDC_RADIOBUTTON_A_TOP           644
#define IDC_RADIOBUTTON_A_VCENTER       645
#define IDC_RADIOBUTTON_A_BOTTOM        646
#define IDC_EDIT_OFFSX                  1000
#define IDC_EDIT_OFFSY                  1001
#define IDC_EDIT_PAGEFILE               1001
#define IDC_EDIT_PATH                   1001
#define IDC_EDIT_TITLE_F1               1001
#define IDC_EDIT_GRAN                   1002
#define IDC_EDIT_TITLE_F2               1002
#define IDC_CHECK_CAM_STOP              1003
#define IDC_EDIT_TITLE_F3               1003
#define IDC_CHECK_CAM_SETUP             1004
#define IDC_EDIT_TITLE_F4               1004
#define IDC_EDIT_RES_WIDTH              1004
#define IDC_CHECK_CAM_PREVIEW           1005
#define IDC_EDIT_TITLE_F5               1005
#define IDC_EDIT_RES_HEIGHT             1005
#define IDC_CHECK_CAM_CAPTURE_AUTO      1006
#define IDC_EDIT_TITLE_F6               1006
#define IDC_CHECK_CAM_CAPTURE_FILE      1007
#define IDC_EDIT_TITLE_F7               1007
#define IDC_CHECK_CAM_PLAY              1008
#define IDC_EDIT_TITLE_F8               1008
#define IDC_CHECK_CAM_WIN_PLAY          1009
#define IDC_EDIT_TITLE_F9               1009
#define IDC_CHECK_CAM_CONNECT           1010
#define IDC_EDIT_TITLE_F10              1010
#define IDC_EDIT_TITLE_F11              1011
#define IDC_GROUPBOX_CAM_MAKE_BTN       1011
#define IDC_CHECK_CAM_SET_TIME          1012
#define IDC_EDIT_TITLE_F12              1012
#define IDC_CHECK_CAM_SHOW_TIME         1013
#define IDC_RADIO_IS_PLC_2              1013
#define IDC_RADIO_IS_PLC_3              1014
#define IDC_CHECK_CAM_PAUSE             1014
#define IDC_RADIO_IS_PLC_4              1015
#define IDC_RADIO_IS_PLC_5              1016
#define IDC_RADIO_IS_PLC_6              1017
#define IDC_RADIO_IS_PLC_7              1018
#define IDC_RADIO_IS_PLC_8              1019
#define IDC_EDIT_START_ANGLE            1020
#define IDC_RADIO_IS_PLC_9              1020
#define IDC_EDIT_RESULT_F1              1021
#define IDC_CHECK_AUTO_OPEN_ALARM       1021
#define IDC_STATIC_STD_M1               1021
#define IDC_EDIT_AMP                    1022
#define IDC_EDIT_RESULT_F2              1022
#define IDC_STATIC_STD_M2               1022
#define IDC_CHECK_USE64BIT              1022
#define IDC_EDIT_RESULT_F3              1023
#define IDC_STATIC_LOCAL_MEM            1023
#define IDC_STATIC_STD_M3               1023
#define IDC_EDIT_RESULT_F4              1024
#define IDC_STATIC_STD_M4               1024
#define IDC_EDIT_RESULT_F5              1025
#define IDC_STATIC_STD_M5               1025
#define IDC_EDIT_RESULT_F6              1026
#define IDC_STATIC_STD_M6               1026
#define IDC_EDIT_RESULT_F7              1027
#define IDC_STATIC_STD_M7               1027
#define IDC_EDIT_RESULT_F8              1028
#define IDC_STATIC_STD_M8               1028
#define IDC_EDIT_RESULT_F9              1029
#define IDC_EDIT_RESULT_F10             1030
#define IDC_EDIT_STD_M1                 1031
#define IDC_EDIT_RESULT_F11             1031
#define IDC_EDIT_STD_M2                 1032
#define IDC_EDIT_RESULT_F12             1032
#define IDC_EDIT_STD_M3                 1033
#define IDC_EDIT_STD_M4                 1034
#define IDC_EDIT_STD_M5                 1035
#define IDC_EDIT_STD_M6                 1036
#define IDC_EDIT_STD_M7                 1037
#define IDC_EDIT_STD_M8                 1038
#define IDC_EDIT_STD_GET_WAFER          1039
#define IDC_EDIT_PRF_WAFER              1040
#define IDC_EDIT_STD_TIT_NOT_OPER       1041
#define IDC_EDIT_STD_MSG_NOT_OPER       1042
#define IDC_EDIT_STD_CAUSE_ALARM        1043
#define IDC_EDIT_STD_CAUSE_END          1044
#define IDC_EDIT_STD_BIT_SS_ADDR        1045
#define IDC_EDIT_STD_BIT_SS_TYPE        1046
#define IDC_LIST_T_ALL                  1047
#define IDC_EDIT_STD_PRPH_OPER          1047
#define IDC_EDIT_T_NAME                 1048
#define IDC_EDIT_STD_ADDR_OPER          1048
#define IDC_EDIT_T_TIMER                1049
#define IDC_EDIT_ADDR_ALTERNATE_CHOOSE_CAUSE 1049
#define IDC_EDIT_T_PREFIX               1050
#define IDC_EDIT_T_EXT                  1051
#define IDC_COMBO_T_TYPE                1052
#define IDC_CHECK_T_HISTORY             1053
#define IDC_CHECK_T_ENABLE_SAVE         1054
#define IDC_EDIT_T_EN_PRF               1055
#define IDC_EDIT_T_EN_ADDR              1056
#define IDC_EDIT_T_EN_TYPE              1057
#define IDC_EDIT_T_EN_NBIT              1058
#define IDC_EDIT_T_EN_OFFS              1059
#define IDC_EDIT_T_TY_PRF               1060
#define IDC_EDIT_T_TY_ADDR              1061
#define IDC_EDIT_T_TY_LEN               1062
#define IDC_EDIT_T_TY_TYPE              1063
#define IDC_LIST_T_TYPE                 1064
#define IDC_BUTTON_T_TY_ADD             1065
#define IDC_BUTTON_T_TY_REM             1066
#define IDC_BUTTON_T_TY_UP              1067
#define IDC_BUTTON_T_TY_DN              1068
#define IDC_EDIT_T_F_PRF                1069
#define IDC_EDIT_T_NAME2                1069
#define IDC_EDIT_T_F_ADDR               1070
#define IDC_EDIT_T_F_NORM               1071
#define IDC_EDIT_T_F_TYPE               1072
#define IDC_EDIT_T_F_DEC                1073
#define IDC_EDIT_T_F_EXPORT             1074
#define IDC_LIST_FIELD                  1075
#define IDC_BUTTON_T_F_ADD              1076
#define IDC_BUTTON_T_F_REM              1077
#define IDC_BUTTON_T_F_UP               1078
#define IDC_BUTTON_T_F_DN               1079
#define IDC_GROUPBOX_FIELD              1080
#define IDC_BUTTON_T_GLOB_ADD           1081
#define IDC_BUTTON_T_GLOB_REM           1082
#define IDC_BUTTON_T_GLOB_MOD           1083
#define IDC_GROUPBOX_T                  1084
#define IDC_EDIT_PS_PRPH                1085
#define IDC_EDIT_T_RES_EXP              1085
#define IDC_EDIT_PS_ADDR                1086
#define IDC_EDIT_MAX_REC                1086
#define IDC_EDIT_PS_TYPE                1087
#define IDC_EDIT_MAX_DIM_FILES          1087
#define IDC_EDIT_PS_BIT                 1088
#define IDC_BUTTON_T_F_MOD              1088
#define IDC_CHECK_PS_PREVIEW            1089
#define IDC_BUTTON_T_F_INSERT           1089
#define IDC_CHECK_PS_SETUP              1090
#define IDC_LIST_WZ_RECIPE              1090
#define IDC_LIST_AS_ALL                 1090
#define IDC_LIST_AL_COLOR_SAMPLE        1090
#define IDC_LIST_OPEN                   1090
#define IDC_LISTVIEW_AD4                1090
#define IDC_LIST_TEXT                   1090
#define IDC_EDIT_T_F_NBIT               1090
#define IDC_EDIT_PS_PRPH_S              1091
#define IDC_LIST_CLOSE                  1091
#define IDC_EDIT_T_F_OFFS               1091
#define IDC_GROUPBOX_A                  1092
#define IDC_EDIT_PS_ADDR_S              1092
#define IDC_BUTTON_T_GLOB_UP            1092
#define IDC_EDIT_PS_LEFT                1093
#define IDC_GROUPBOX_RA                 1093
#define IDC_BUTTON_T_GLOB_DN            1093
#define IDC_EDIT_PS_BOTTOM              1094
#define IDC_BUTTON_T_F_COPY             1094
#define IDC_EDIT_SA_HFONT               1095
#define IDC_GROUPBOX_PS                 1095
#define IDC_BUTTON_T_F_PASTE            1095
#define IDC_EDIT_SA_HROW                1096
#define IDC_EDIT_PV_ID                  1096
#define IDC_EDIT_SA_NAMEFONT            1097
#define IDC_EDIT_PS_TOP2                1097
#define IDC_EDIT_SA_X_1                 1098
#define IDC_EDIT_PS_RIGHT2              1098
#define IDC_CHECK_SA_PREVIEW            1099
#define IDC_CHECK_PV_PREVIEW            1099
#define IDC_GROUPBOX_VIS                1100
#define IDC_CHECK_SA_SETUP              1100
#define IDC_CHECK_PV_SETUP              1100
#define IDC_BUTTON_PATH                 1101
#define IDC_STATICTEXT1_VIS             1101
#define IDC_EDIT_SA_TOP                 1101
#define IDC_EDIT_CC_C_1                 1101
#define IDC_GROUPBOX_PS2                1101
#define IDC_STATICTEXT2_VIS             1102
#define IDC_EDIT_SA_RIGHT               1102
#define IDC_EDIT_CC_C_2                 1102
#define IDC_EDIT_PS_TYPE_S              1102
#define IDC_STATICTEXT3_VIS             1103
#define IDC_EDIT_SA_LEFT                1103
#define IDC_EDIT_CC_C_3                 1103
#define IDC_EDIT_PS_BIT_S               1103
#define IDC_STATICTEXT4_VIS             1104
#define IDC_EDIT_SA_BOTTOM              1104
#define IDC_EDIT_CC_C_4                 1104
#define IDC_BUTTON_T_INFO_FILE          1104
#define IDC_COMBOBOX_VIS_PERIFS         1105
#define IDC_EDIT_SA_AL_1                1105
#define IDC_EDIT_CC_C_5                 1105
#define IDC_EDIT_PS_PRPH_N              1105
#define IDC_EDIT_VIS_ADDR               1106
#define IDC_EDIT_SA_TXT_1               1106
#define IDC_EDIT_CC_C_6                 1106
#define IDC_EDIT_PS_ADDR_N              1106
#define IDC_EDIT_VIS_NBITS              1107
#define IDC_EDIT_SA_X_3                 1107
#define IDC_LIST_GR_TEXT                1107
#define IDC_EDIT_CC_C_7                 1107
#define IDC_EDIT_PS_LEN_N               1107
#define IDC_EDIT_VIS_OFFSET             1108
#define IDC_EDIT_SA_AL_3                1108
#define IDC_BUTTON_GR_MOD_LIST_TEXT     1108
#define IDC_EDIT_CC_C_8                 1108
#define IDC_EDIT_PS_DEF_FILE_N          1108
#define IDC_EDIT_CC_V_1                 1109
#define IDC_CHECKBOX_VIS_NEGATIVE       1109
#define IDC_EDIT_SA_TXT_3               1109
#define IDC_EDIT_GR_XSCALE              1109
#define IDC_LIST_RCP_SEND_COPY          1109
#define IDC_BUTTON_T_TEMPL_FILE         1109
#define IDC_BUTTON_MODELESS             1110
#define IDC_EDIT_SA_X_2                 1110
#define IDC_EDIT_CC_V_2                 1110
#define IDC_CHECK_GR_FIX                1110
#define IDC_STATIC_READY_BITS_OR_OFFSET 1110
#define IDC_GROUPBOX_VIS2               1110
#define IDC_BUTTON_BTN_CHOOSE_ACTION    1111
#define IDC_EDIT_SA_AL_2                1111
#define IDC_EDIT_CC_V_3                 1111
#define IDC_COMBO_GR_FIX_TIME           1111
#define IDC_EDIT_AL_COLOR_R_FG          1111
#define IDC_COMBOBOX_BTN_CHOOSE_ACTION  1112
#define IDC_EDIT_SA_TXT_2               1112
#define IDC_EDIT_CC_V_4                 1112
#define IDC_CHECK_GR_HISTORY            1112
#define IDC_EDIT_AL_COLOR_G_FG          1112
#define IDC_RADIOBUTTON_VAR_TEXT_VALUE  1113
#define IDC_EDIT_SA_X_4                 1113
#define IDC_EDIT_CC_V_5                 1113
#define IDC_CHECK_GR_LOCAL              1113
#define IDC_EDIT_AL_COLOR_R_FG2         1113
#define IDC_BUTTON_PERSONALIZE          1113
#define IDC_EDIT_SA_AL_4                1114
#define IDC_EDIT_CC_V_6                 1114
#define IDC_CHECK_GR_PREVIEW            1114
#define IDC_RADIOBUTTON_VAR_TEXT_VALUE2 1114
#define IDC_EDIT_AL_COLOR_G_FG2         1114
#define IDC_COMBOBOX_PSWLEVEL           1115
#define IDC_EDIT_SA_TXT_4               1115
#define IDC_EDIT_CC_V_7                 1115
#define IDC_CHECK_GR_SETUP              1115
#define IDC_STATICTEXT_PSWLEVEL         1116
#define IDC_EDIT_SRA_HFONT              1116
#define IDC_EDIT_CC_V_8                 1116
#define IDC_EDIT_GR_HFONT               1116
#define IDC_EDIT_AL_COLOR_B_FG          1116
#define IDC_CHECKBOX_PSWLEVEL           1117
#define IDC_EDIT_SRA_HROW               1117
#define IDC_CHECK_GR_ITALIC             1117
#define IDC_EDIT_AL_COLOR_R_BG          1117
#define IDC_EDIT_BTN_MODELESS           1118
#define IDC_EDIT_SRA_NAMEFONT           1118
#define IDC_EDIT_GR_PATH                1118
#define IDC_EDIT_AL_COLOR_G_BG          1118
#define IDC_EDIT_SRA_X_1                1119
#define IDC_EDIT_GR_NAMEFONT            1119
#define IDC_EDIT_AL_COLOR_B_BG          1119
#define IDC_CHECK_SRA_PREVIEW           1120
#define IDC_EDIT_GR_FILE_RANGE          1120
#define IDC_EDIT_AL_COLOR_B_FG2         1120
#define IDC_CHECK_SRA_SETUP             1121
#define IDC_EDIT_GR_TREND_NAME          1121
#define IDC_EDIT_AL_COLOR_R_BG2         1121
#define IDC_EDIT_SRA_TOP                1122
#define IDC_CHECK_GR_UNIQUE_RANGE       1122
#define IDC_EDIT_AL_COLOR_G_BG2         1122
#define IDC_EDIT_SRA_RIGHT              1123
#define IDC_CHECK_GR_LINE_TYPE          1123
#define IDC_EDIT_AL_COLOR_B_BG2         1123
#define IDC_EDIT_SRA_LEFT               1124
#define IDC_STATIC_LINE_TYPE            1124
#define IDC_EDIT_AL_PERC_1              1124
#define IDC_EDIT_SRA_BOTTOM             1125
#define IDC_EDIT_GR_N_ROW_LINE          1125
#define IDC_EDIT_AL_PERC_2              1125
#define IDC_EDIT_SRA_AL_1               1126
#define IDC_EDIT_GR_ROUND_LINE          1126
#define IDC_EDIT_AL_PERC_3              1126
#define IDC_EDIT_SRA_TXT_1              1127
#define IDC_EDIT_GR_DIM_HEADER          1127
#define IDC_EDIT_AL_PERC_4              1127
#define IDC_EDIT_SRA_X_3                1128
#define IDC_EDIT_GR_OFFS_STRUCT         1128
#define IDC_EDIT_AL_PERC_5              1128
#define IDC_EDIT_SRA_AL_3               1129
#define IDC_CHECK_GR_BOLD               1129
#define IDC_EDIT_AL_PERC_6              1129
#define IDC_EDIT_SRA_TXT_3              1130
#define IDC_STATIC_GR_CURR_COLOR        1130
#define IDC_EDIT_AL_PERC_7              1130
#define IDC_EDIT_SRA_X_2                1131
#define IDC_STATIC_GR_BASE_R            1131
#define IDC_EDIT_AL_PERC_8              1131
#define IDC_EDIT_SRA_AL_2               1132
#define IDC_STATIC_GR_BASE_G            1132
#define IDC_EDIT_AL_PERC_9              1132
#define IDC_EDIT_SRA_TXT_2              1133
#define IDC_STATIC_GR_BASE_B            1133
#define IDC_EDIT_AL_POS_1               1133
#define IDC_EDIT_SRA_X_4                1134
#define IDC_BUTTON_GR_SAVE              1134
#define IDC_EDIT_AL_POS_2               1134
#define IDC_EDIT_SRA_AL_4               1135
#define IDC_CHECK_GR_UNDERL             1135
#define IDC_EDIT_AL_POS_3               1135
#define IDC_EDIT_SRA_TXT_4              1136
#define IDC_EDIT_GR_N_LABEL             1136
#define IDC_BUTTON_RCP_SEND_ADD         1136
#define IDC_EDIT_AL_POS_4               1136
#define IDC_EDIT_GR_DEC_LABEL           1137
#define IDC_BUTTON_RCP_SEND_REM         1137
#define IDC_EDIT_AL_POS_5               1137
#define IDC_STATIC_COD                  1138
#define IDC_BUTTON_RCP_SEND_UP          1138
#define IDC_COMBO_GR_TIME_PSW           1138
#define IDC_EDIT_AL_POS_6               1138
#define IDC_STATIC_INFO                 1139
#define IDC_BUTTON_RCP_SEND_DN          1139
#define IDC_EDIT_GR_TIME_REFRESH        1139
#define IDC_EDIT_AL_POS_7               1139
#define IDC_EDIT_TEXT                   1140
#define IDC_BUTTON_RCP_DEF_ADD          1140
#define IDC_EDIT_WZ_RCP_INIT_ADDR       1140
#define IDC_EDIT_LAB_RROW_1             1140
#define IDC_EDIT_RROW_FILENAME          1140
#define IDC_EDIT_AS_TEXT                1140
#define IDC_EDIT_AL_POS_8               1140
#define IDC_EDIT_COL1                   1140
#define IDC_EDIT_COL_2_1                1140
#define IDC_COMBO_GR_TREND_NAME         1140
#define IDC_EDIT_TICK_TOP               1140
#define IDC_EDIT_NUM_DEC                1140
#define IDC_EDIT_ZERO_MIN               1140
#define IDC_EDIT_USE_FILE_MIN_MAX       1140
#define IDC_COMBO_RCP_PRPH_MEM          1141
#define IDC_EDIT_WZ_RCP_LEN_NAME        1141
#define IDC_EDIT_LAB_RROW_2             1141
#define IDC_EDIT_AL_POS_9               1141
#define IDC_EDIT_COL2                   1141
#define IDC_EDIT_COL_2_2                1141
#define IDC_EDIT_ZERO_MAX               1141
#define IDC_EDIT_RCP_INIT_MEM           1142
#define IDC_EDIT_WZ_RCP_DIM             1142
#define IDC_EDIT_LAB_RROW_3             1142
#define IDC_EDIT_COL3                   1142
#define IDC_EDIT_COL_2_3                1142
#define IDC_EDIT_TICK_BOTTOM            1142
#define IDC_EDIT_RCP_ADDR_NAME          1143
#define IDC_EDT_WZ_RCP_ADDR_PRPH        1143
#define IDC_EDIT_LAB_RROW_4             1143
#define IDC_EDIT_HROW                   1143
#define IDC_EDIT_COL_2_4                1143
#define IDC_EDIT_TICK_LEFT              1143
#define IDC_EDIT_RCP_LEN_NAME           1144
#define IDC_EDT_WZ_RCP_ADDR_LB          1144
#define IDC_EDIT_LAB_RROW_5             1144
#define IDC_EDIT_WCOL1                  1144
#define IDC_EDIT_COL_2_5                1144
#define IDC_EDIT_TICK_RIGHT             1144
#define IDC_EDIT_RCP_ADDR_ACTIVE        1145
#define IDC_EDIT_WZ_RCP_LABEL           1145
#define IDC_EDIT_LAB_RROW_6             1145
#define IDC_EDIT_WCOL2                  1145
#define IDC_EDIT_COL_2_6                1145
#define IDC_EDT_WZ_LKP_NBIT             1145
#define IDC_COMBO_RCP_PSW_LEVEL         1146
#define IDC_EDIT_WZ_RCP_LABEL_FLT       1146
#define IDC_EDIT_LAB_RROW_7             1146
#define IDC_EDIT_WCOL3                  1146
#define IDC_EDIT_COL_2_7                1146
#define IDC_COMBO_RCP_PRPH_SEND         1147
#define IDC_EDIT_LAB_RROW_8             1147
#define IDC_EDIT_COL_2_8                1147
#define IDC_EDT_WZ_LKP_OFFS             1147
#define IDC_COMBO_RCP_PRPH_COPY         1148
#define IDC_EDIT_LAB_RROW_9             1148
#define IDC_EDIT_COL_2_9                1148
#define IDC_EDIT_RCP_ADDR_SEND          1149
#define IDC_EDIT_LAB_RROW_10            1149
#define IDC_EDIT_COL_2_10               1149
#define IDC_EDIT_RCP_DIM_SEND           1150
#define IDC_EDIT_LAB_RROW_11            1150
#define IDC_EDIT_COL_2_11               1150
#define IDC_COMBO_RCP_TYPE_SEND         1151
#define IDC_EDIT_LAB_RROW_12            1151
#define IDC_EDIT_COL_2_12               1151
#define IDC_EDIT_RCP_ADDR_COPY          1152
#define IDC_EDIT_LAB_RROW_13            1152
#define IDC_EDIT_COL_2_13               1152
#define IDC_COMBO_RCP_TYPE_DEF          1153
#define IDC_EDIT_LAB_RROW_14            1153
#define IDC_EDIT_COL_2_14               1153
#define IDC_EDIT_RCP_DIM_COPY           1154
#define IDC_EDIT_LAB_RROW_15            1154
#define IDC_EDIT_COL_2_15               1154
#define IDC_COMBO_RCP_TYPE_COPY         1155
#define IDC_EDIT_LAB_RROW_16            1155
#define IDC_EDIT_COL_2_16               1155
#define IDC_EDIT_RCP_ADDR_DEF           1156
#define IDC_EDIT_LAB_RROW_17            1156
#define IDC_EDIT_COL_3_1                1156
#define IDC_EDIT_RCP_DIM_DEF            1157
#define IDC_EDIT_LAB_RROW_18            1157
#define IDC_EDIT_COL_3_2                1157
#define IDC_COMBO_RCP_ALIGN_LB          1158
#define IDC_EDIT_LAB_RROW_19            1158
#define IDC_EDIT_COL_3_3                1158
#define IDC_LIST_RCP_TEXT               1159
#define IDC_EDIT_LAB_RROW_20            1159
#define IDC_EDIT_COL_3_4                1159
#define IDC_EDIT_RCP_VAL_DEF            1160
#define IDC_EDIT_COL_3_5                1160
#define IDC_LIST_RCP_DEF                1161
#define IDC_EDIT_COL_3_6                1161
#define IDC_EDIT_RCP_NUM_LB             1162
#define IDC_EDIT_COL_3_7                1162
#define IDC_EDIT_COL_3_8                1163
#define IDC_EDIT_RCP_DIM_LB             1163
#define IDC_EDIT_COL_3_9                1164
#define IDC_EDIT_RCP_DEC_LB             1164
#define IDC_EDIT_COL_3_10               1165
#define IDC_EDIT_RCP_ADDR_LB            1165
#define IDC_EDIT_COL_3_11               1166
#define IDC_EDIT_RCP_HFONT              1166
#define IDC_EDIT_COL_3_12               1167
#define IDC_LIST_RCP_LB                 1167
#define IDC_EDIT_COL_3_13               1168
#define IDC_BUTTON_RCP_DEF_REM          1168
#define IDC_EDIT_COL_3_14               1169
#define IDC_BUTTON_RCP_DEF_UP           1169
#define IDC_EDIT_COL_3_15               1170
#define IDC_BUTTON_RCP_DEF_DN           1170
#define IDC_EDIT_COL_3_16               1171
#define IDC_BUTTON_RCP_LB_ADD           1171
#define IDC_BUTTON_RCP_LB_REM           1172
#define IDC_BUTTON_RCP_LB_UP            1173
#define IDC_BUTTON_RCP_LB_DN            1174
#define IDC_BUTTON_RCP_MOD_LIST_TEXT    1175
#define IDC_EDIT_RCP_NAMEFONT           1176
#define IDC_CHECK_RCP_UNDERL            1177
#define IDC_CHECK_RCP_ITALIC            1178
#define IDC_CHECK_RCP_BOLD              1179
#define IDC_BUTTON_RCP_SAVE             1180
#define IDC_STATIC_RCP_1                1181
#define IDC_EDIT_ADDR_RROW_1            1181
#define IDC_STATIC_RCP_2                1182
#define IDC_EDIT_ADDR_RROW_2            1182
#define IDC_STATIC_RCP_3                1183
#define IDC_EDIT_ADDR_RROW_3            1183
#define IDC_STATIC_RCP_4                1184
#define IDC_EDIT_ADDR_RROW_4            1184
#define IDC_STATIC_RCP_5                1185
#define IDC_EDIT_ADDR_RROW_5            1185
#define IDC_STATIC_RCP_6                1186
#define IDC_EDIT_ADDR_RROW_6            1186
#define IDC_STATIC_RCP_7                1187
#define IDC_EDIT_ADDR_RROW_7            1187
#define IDC_STATIC_RCP_8                1188
#define IDC_EDIT_ADDR_RROW_8            1188
#define IDC_EDIT_RCP_ADDR_ACT           1189
#define IDC_EDIT_ADDR_RROW_9            1189
#define IDC_COMBO_RCP_PRPH_ACT          1190
#define IDC_EDIT_ADDR_RROW_10           1190
#define IDC_EDIT_RCP_BIT_ACT            1191
#define IDC_EDIT_ADDR_RROW_11           1191
#define IDC_EDIT_RCP_ADDR_ENA           1192
#define IDC_EDIT_ADDR_RROW_12           1192
#define IDC_COMBO_RCP_PRPH_ENA          1193
#define IDC_EDIT_ADDR_RROW_13           1193
#define IDC_EDIT_RCP_BIT_ENA            1194
#define IDC_EDIT_ADDR_RROW_14           1194
#define IDC_STATIC_NORM_DIM             1195
#define IDC_EDIT_ADDR_RROW_15           1195
#define IDC_COMBO_RCP_TYPE_ON_MEM       1196
#define IDC_EDIT_ADDR_RROW_16           1196
#define IDC_STATIC_CURR_SEND            1197
#define IDC_EDIT_ADDR_RROW_17           1197
#define IDC_BUTTON_RCP_SEND_MOD         1198
#define IDC_COMBO_WZ_RCP_MEM            1198
#define IDC_EDIT_ADDR_RROW_18           1198
#define IDC_BUTTON_RCP_DEF_MOD          1199
#define IDC_COMBO_WZ_RCP_PRPH           1199
#define IDC_EDIT_ADDR_RROW_19           1199
#define IDC_BUTTON_RCP_LB_MOD           1200
#define IDC_COMBO_WZ_RCP_TYPE_MEM       1200
#define IDC_EDIT_ADDR_RROW_20           1200
#define IDC_RADIOBUTTON_HEADER          1201
#define IDC_COMBO_WZ_RCP_TYPE_PRPH      1201
#define IDC_STATIC_RCP_9                1201
#define IDC_RADIOBUTTON_BODY            1202
#define IDC_CHECK_IN_LB                 1202
#define IDC_EDIT_RCP_EXT                1202
#define IDC_CHECK_ENABLE_LANG           1202
#define IDC_CHECK_RROW_USE_FIRST_TXT    1202
#define IDC_ALL                         1202
#define IDC_CHECK_TOUCH_SCREEN          1202
#define IDC_CHECK_COL_BKG               1202
#define IDC_CHECK_AL_ID                 1202
#define IDC_CHECK_OFFSET                1202
#define IDC_CHECK_USE_PANEL             1202
#define IDC_CHECK_SWAP                  1202
#define IDC_CHECK_VISIB                 1202
#define IDC_CHECK_THEME                 1202
#define IDC_CHECK_VIS_TOP               1202
#define IDC_CHECK_SCALED_BMP            1202
#define IDC_CHECK_USE_CUSTOM_SEND       1202
#define IDC_CHECK_ONLY_ONE_FILE         1202
#define IDC_CHECK_RET                   1202
#define IDC_CHECK_WZ_PLK_OPEN_PAGE      1202
#define IDC_CHECK_CENTER_ZERO           1202
#define IDC_CHECK_USE_FILE_MIN_MAX      1202
#define IDC_CHECK_FIXED_FILE            1202
#define IDC_CHECK_TITLE_OR_SIMPLE       1202
#define IDC_CHECK_USE_NUMBER_SEPARATOR  1202
#define IDC_HORZ                        1202
#define IDC_CHECK_ENABLE_MOV            1202
#define IDC_CHECK_RELATIVE_DIM          1202
#define IDC_BUTTON_WZ_RCP_MOD           1203
#define IDC_CHECK_COL_GRID              1203
#define IDC_CHECK_AL_STAT               1203
#define IDC_CHECK_OTHER                 1203
#define IDC_CHECK_FLAT                  1203
#define IDC_EDIT_RCP_EDITOR_EXT         1203
#define IDC_CHECK_SIMPLE_BORDER         1203
#define IDC_CHECK_STRETCHED_BMP         1203
#define IDC_VERT                        1203
#define IDC_BUTTON_WZ_RCP_ADD           1204
#define IDC_CHECK_COL_AXES              1204
#define IDC_CHECK_AL_TIME               1204
#define IDC_CHECK_NO_PRPH1              1204
#define IDC_CHECK_NO_BORDER             1204
#define IDC_CHECK_VIS_BOTTOM            1204
#define IDC_EDIT_SUB_PATH               1204
#define IDC_BUTTON_WZ_RCP_REM           1205
#define IDC_CHECK_AL_FILTER             1205
#define IDC_CHECK_VIS_LEFT              1205
#define IDC_CHECK_VISIB_PRPH            1205
#define IDC_EDIT_ABS_PATH               1205
#define IDC_BUTTON_WZ_RCP_UP            1206
#define IDC_CHECK_AL_ID_GRP             1206
#define IDC_CHECK_VIS_RIGHT             1206
#define IDC_CHECK_USE_ADDR              1206
#define IDC_BUTTON_RCP_LB_COPY          1206
#define IDC_BUTTON_WZ_RCP_DN            1207
#define IDC_CHECK_AL_DESCR_GRP          1207
#define IDC_CHECK_USE_PRPH              1207
#define IDC_BUTTON_RCP_LB_PASTE         1207
#define IDC_RADIO_WZ_FIRST_TREND        1208
#define IDC_CHECK_AL_PRPH               1208
#define IDC_CHECK_SIMPLE_TXT            1208
#define IDC_STATIC_RCP_10               1208
#define IDC_RADIO_WZ_FIRST_MAINT        1209
#define IDC_BUTTON_NEXT                 1209
#define IDC_CHECK_AL_DESCR_AL           1209
#define IDC_CHECK_PRPH_FILTER           1209
#define IDC_EDIT_RCP_ADDR_BIT_FUNCT     1209
#define IDC_RADIO_WZ_FIRST_RECIPE       1210
#define IDC_BUTTON_PREV                 1210
#define IDC_CHECK_AL_DATE               1210
#define IDC_CHECK_SUBST_VAR             1210
#define IDC_COMBO_RCP_PRPH_BIT_FUNCT    1210
#define IDC_STATICTEXT_1                1211
#define IDC_RADIO_WZ_FIRST_RECIPE_LB    1211
#define IDC_CHECK_AL_USE_LBOX           1211
#define IDC_COMBO_RCP_TYPE_BIT_FUNCT    1211
#define IDC_STATICTEXT_2                1212
#define IDC_RADIO_WZ_FIRST_RECIPE_ROW   1212
#define IDC_STATICTEXT_3                1213
#define IDC_RADIO_WZ_LINKED_PAGE        1213
#define IDC_STATICTEXT_4                1214
#define IDC_STATIC_TRUE_INIT_ADDR       1214
#define IDC_STATICTEXT_5                1215
#define IDC_RADIO_WZ_WIN_FIX            1215
#define IDC_STATICTEXT_6                1216
#define IDC_RADIO_WZ_WIN_VAR            1216
#define IDC_STATICTEXT_7                1217
#define IDC_RADIO_WZ_FIX_HOUR           1217
#define IDC_STATICTEXT_8                1218
#define IDC_RADIO_WZ_FIX_MINUTE         1218
#define IDC_STATICTEXT_9                1219
#define IDC_RADIO_WZ_FIX_FT             1219
#define IDC_STATICTEXT_10               1220
#define IDC_STATICTEXT_11               1221
#define IDC_RADIO_LANG_1                1221
#define IDC_CHECK_FORCE_CHANGE          1222
#define IDC_STATICTEXT_12               1222
#define IDC_RADIO_LANG_2                1222
#define IDC_STATIC_L1                   1222
#define IDC_STATICTEXT_13               1223
#define IDC_RADIO_LANG_3                1223
#define IDC_STATIC_L2                   1223
#define IDC_STATICTEXT_14               1224
#define IDC_RADIO_LANG_4                1224
#define IDC_STATIC_L3                   1224
#define IDC_STATICTEXT_15               1225
#define IDC_RADIO_LANG_5                1225
#define IDC_STATIC_L4                   1225
#define IDC_STATICTEXT_16               1226
#define IDC_RADIO_LANG_6                1226
#define IDC_STATIC_L5                   1226
#define IDC_BUTTON_SAVE                 1227
#define IDC_RADIO_LANG_7                1227
#define IDC_STATIC_L6                   1227
#define IDC_RADIO_LANG_8                1228
#define IDC_STATIC_L7                   1228
#define IDC_RADIO_LANG_9                1229
#define IDC_STATIC_L8                   1229
#define IDC_RADIO_LANG_10               1230
#define IDC_STATIC_L9                   1230
#define IDC_STATIC_L10                  1231
#define IDC_COMBO_RROW_EDIT_MEM         1234
#define IDC_COMBO_RROW_NROW             1235
#define IDC_COMBO_RROW_NCOL             1236
#define IDC_COMBO_RROW_PSW_SEND         1237
#define IDC_COMBO_RROW_PSW_SAVE         1238
#define IDC_COMBO_RROW_PRPH_SAVE_ACTIVE 1239
#define IDC_COMBO_RROW_PRPH_ACTIVE      1241
#define IDC_COMBO_RROW_TYPE_ACTIVE      1242
#define IDC_COMBO_RROW_PRPH_ENABLE      1243
#define IDC_COMBO_RROW_TYPE_ENABLE      1244
#define IDC_STATIC_LABEL_2              1255
#define IDC_STATIC_LABEL_3              1256
#define IDC_EDIT_RROW_ADDR_SAVE_ACTIVE  1256
#define IDC_EDIT_RROW_ADDR_ACTIVE       1257
#define IDC_EDIT_RROW_NBIT_ACTIVE       1258
#define IDC_EDIT_RROW_OFFS_ACTIVE       1259
#define IDC_EDIT_RROW_ADDR_ENABLE       1260
#define IDC_EDIT_RROW_NBIT_ENABLE       1261
#define IDC_EDIT_RROW_OFFS_ENABLE       1262
#define IDC_EDIT_RROW_ADDR_PLC_NUM_ACTIVE 1263
#define IDC_EDIT_RROW_ADDR_ADDR_INIT    1264
#define IDC_BUTTON_RROW_SAVE            1284
#define IDC_BUTTON_XSCOPE_BKG           1284
#define IDC_BUTTON_AS_MOVEUP            1284
#define IDC_TBL_INFO_HEADER             1284
#define IDC_FG                          1284
#define IDC_BTN_COLOR_TOP               1284
#define IDC_BUTTON_RELOAD_DEC           1284
#define IDC_BUTTON_LNK_CHOOSE_PAGE      1284
#define IDC_BUTTON_XSCOPE_GRID          1285
#define IDC_BUTTON_AS_MOVEDN            1285
#define IDC_TBL_INFO_FIRST_COL          1285
#define IDC_BG                          1285
#define IDC_BTN_COLOR_BKG               1285
#define IDC_BUTTON_LNK_CHOOSE_PAGE_BTN  1285
#define IDC_BUTTON_XSCOPE_AXES          1286
#define IDC_BUTTON_AS_ADD_TEXT          1286
#define IDC_TBL_INFO_ROWS               1286
#define IDC_FONT                        1286
#define IDC_BTN_COLOR_BOTTOM            1286
#define IDC_STATIC_RROW_IF_FIRST_TEXT   1287
#define IDC_BUTTON_XSCOPE_LINE1         1287
#define IDC_BUTTON_AS_REM_TEXT          1287
#define IDC_BTN_OFF                     1287
#define IDC_BTN_COLOR_LEFT              1287
#define IDC_SKIP                        1288
#define IDC_BUTTON_XSCOPE_LINE2         1288
#define IDC_BTN_ON                      1288
#define IDC_BTN_COLOR_RIGHT             1288
#define IDC_APPLY                       1289
#define IDC_FG_ON                       1289
#define IDC_INFO_OBJ                    1290
#define IDC_BG_ON                       1290
#define IDC_CHECK_DEF_EDITOR            1291
#define IDC_CHECK_UNIQUE_DATA           1291
#define IDC_CHECK_NO_SENDBIT1           1291
#define IDC_CHECK_WZ_LKP_MODAL          1291
#define IDC_CHECK_OFFS_PROGR            1291
#define IDC_CHECK_PS_FULL               1291
#define IDC_SAMPLE_XSCOPE               1292
#define IDC_CHECK_NO_SENDBIT2           1292
#define IDC_CHECK_OFFS_PROGR_ADDR       1292
#define IDC_CHECK_SS_FULL               1292
#define IDC_STATIC_PAGE_NUM             1293
#define IDC_CHECK_NO_SENDBIT3           1293
#define IDC_GROUPBOX_PS3                1294
#define IDC_CHECK_NO_SENDBIT4           1294
#define IDC_STATIC_GROUP                1295
#define IDC_CHECK_NO_SENDBIT5           1295
#define IDC_STATIC_FILTER               1296
#define IDC_LIST_AS_ROW                 1296
#define IDC_CHECK_NO_SENDBIT6           1296
#define IDC_STATIC_AS_RETURN            1297
#define IDC_CHECK_NO_SENDBIT7           1297
#define IDC_STATIC_ASSOC                1297
#define IDC_EDIT_AS_ID                  1298
#define IDC_CHECK_NO_SENDBIT8           1298
#define IDC_SLIDER_AL_R                 1299
#define IDC_CHECK_NO_MMAP_FILE1         1299
#define IDC_SLIDER_AL_G                 1300
#define IDC_CHECK_NO_MMAP_FILE2         1300
#define IDC_STATIC_NDEC                 1301
#define IDC_CHECK_NO_MMAP_FILE3         1301
#define IDC_SLIDER_AL_B                 1302
#define IDC_CHECK_NO_MMAP_FILE4         1302
#define IDC_STATIC_AL_CURR_COLOR        1303
#define IDC_CHECK_NO_MMAP_FILE5         1303
#define IDC_STATIC_AL_CL_FG             1304
#define IDC_CHECK_NO_MMAP_FILE6         1304
#define IDC_STATIC_AL_CL_BG             1305
#define IDC_CHECK_NO_MMAP_FILE7         1305
#define IDC_STATIC_AL_CL_FG2            1306
#define IDC_CHECK_NO_MMAP_FILE8         1306
#define IDC_STATIC_AL_CL_BG2            1307
#define IDC_CHECK_NO_MMAP_FILE9         1307
#define IDC_STATIC_CURR_AL_TEXT         1308
#define IDC_BUTTON_TREND_BKG            1309
#define IDC_BUTTON_TREND_LINE_COLOR     1310
#define IDC_EDIT_NUM_ROW_TREND          1311
#define IDC_EDIT_NUM_COL_TREND          1312
#define IDC_SAMPLE_TREND                1313
#define IDC_BUTTON_TREND_CHOOSE         1314
#define IDC_BUTTON_TREND_LINE_BAR       1315
#define IDC_STATIC_TREND_NAME           1316
#define IDC_BUTTON_TREND_GRID           1317
#define IDC_LISTBOX_TREND               1318
#define IDC_STATIC_VALUE                1319
#define IDC_EDIT_VALUE                  1320
#define IDC_BUTTON_ADD_OPEN             1321
#define IDC_BUTTON_REM_OPEN             1322
#define IDC_STATIC_PAG_FONT             1322
#define IDC_STATIC_VALUE2               1323
#define IDC_STATIC_PAG_COL_NORM         1323
#define IDC_BUTTON_UP_OPEN              1324
#define IDC_STATIC_PAG_COL_SEL          1324
#define IDC_EDIT_ID_SPIN                1324
#define IDC_BUTTON_DN_OPEN              1325
#define IDC_STATIC_PAG_FONT2            1325
#define IDC_BUTTON_ADD_CLOSE            1326
#define IDC_EDIT_SPIN_DELAY             1326
#define IDC_RADIO_INCR                  1326
#define IDC_BUTTON_REM_CLOSE            1327
#define IDC_EDIT_SPIN_STEP              1327
#define IDC_RADIO_DECR                  1327
#define IDC_RADIO1                      1327
#define IDC_STATIC_VALUE3               1328
#define IDC_EDIT_SPIN_MEM_ADDR          1328
#define IDC_RADIO2                      1328
#define IDC_LISTBOX_VARS_TRAY           1328
#define IDC_BUTTON_UP_CLOSE             1329
#define IDC_EDIT_SPIN_STEP_DECR         1329
#define IDC_RADIO1_1                    1329
#define IDC_EDIT_TRAY_ADDR              1329
#define IDC_RADIO1_SHOW_LAMP            1329
#define IDC_RADIO3                      1329
#define IDC_BUTTON_DN_CLOSE             1330
#define IDC_RADIO2_1                    1330
#define IDC_EDIT_TRAY_NBIT              1330
#define IDC_RADIO2_SWAP                 1330
#define IDC_RADIO4                      1330
#define IDC_RADIO3_1                    1331
#define IDC_COMBOBOX_TRAY_PRPH          1331
#define IDC_RADIO2_HIDE_LAMP            1331
#define IDC_RADIO4_1                    1332
#define IDC_BUTTON_ADD_TRAY             1332
#define IDC_RADIO2_SHOW_LAMP            1332
#define IDC_RADIO1_2                    1333
#define IDC_BUTTON_REM_TRAY             1333
#define IDC_RADIO2_2                    1334
#define IDC_BUTTON_UP_TRAY              1334
#define IDC_STATIC_IX_RROW_1            1335
#define IDC_RADIO3_2                    1335
#define IDC_BUTTON_DN_TRAY              1335
#define IDC_COMBO_ALIGN                 1335
#define IDC_STATIC_IX_RROW_2            1336
#define IDC_RADIO4_2                    1336
#define IDC_EDIT_PSW_ADDR               1336
#define IDC_STATIC_IX_RROW_3            1337
#define IDC_COMBOBOX_PSW_PRPH           1337
#define IDC_STATIC_IX_RROW_4            1338
#define IDC_STATIC_SAMPLE               1338
#define IDC_EDIT_PING_ADDR              1338
#define IDC_STATIC_IX_RROW_5            1339
#define IDC_EDIT_TEXT_OFF               1339
#define IDC_COMBOBOX_PING_PRPH          1339
#define IDC_STATIC_IX_RROW_6            1340
#define IDC_EDIT_TEXT_ON                1340
#define IDC_STATIC_IX_RROW_7            1341
#define IDC_EDIT_BMP_OFF                1341
#define IDC_STATIC_IX_RROW_8            1342
#define IDC_EDIT_BMP_ON                 1342
#define IDC_STATIC_IX_RROW_9            1343
#define IDC_RADIO_USE_TEXT              1343
#define IDC_STATIC_IX_RROW_10           1344
#define IDC_RADIO_USE_BMP               1344
#define IDC_STATIC_IX_RROW_11           1345
#define IDC_RADIO_NO_REDIM              1345
#define IDC_STATIC_IX_RROW_12           1346
#define IDC_RADIO_SCALE                 1346
#define IDC_STATIC_IX_RROW_13           1347
#define IDC_RADIO_DISTORCE              1347
#define IDC_STATIC_IX_RROW_14           1348
#define IDC_STATIC_SAMPLE_COLOR_ON      1348
#define IDC_STATIC_IX_RROW_15           1349
#define IDC_STATIC_IX_RROW_16           1350
#define IDC_STATIC_IX_RROW_17           1351
#define IDC_STATIC_SAMPLE_FONT          1351
#define IDC_STATIC_IX_RROW_18           1352
#define IDC_FG_OFF                      1352
#define IDC_STATIC_IX_RROW_19           1353
#define IDC_BG_OFF                      1353
#define IDC_STATIC_IX_RROW_20           1354
#define IDC_STATIC_SAMPLE_COLOR_OFF     1354
#define IDC_STATIC_IMG_XMETER           1355
#define IDC_EDIT_H_ROW                  1355
#define IDC_RADIO1_HIDE_SHOW            1356
#define IDC_PASTE                       1356
#define IDC_RADIO1_HIDE_LAMP            1357
#define IDC_COPY_TO_CLIP                1357
#define IDC_RADIO_ASCII                 1358
#define IDC_RADIO_HEX                   1359
#define IDC_EDIT_ASCII                  1360
#define IDC_EDIT_HEX                    1361
#define IDC_STATIC_PRG                  1362
#define IDC_COMBO_POS_BMP               1363
#define IDC_EDIT_RROW_ADDR_PLC_1        1364
#define IDC_STATIC_TEST_COLOR           1364
#define IDC_EDIT_RROW_ADDR_PLC_2        1365
#define IDC_EDIT_RROW_ADDR_PLC_3        1366
#define IDC_EDIT_RECIPE_NOTE            1366
#define IDC_EDIT_RROW_ADDR_PLC_4        1367
#define IDC_STATIC_PANEL                1367
#define IDC_EDIT_RROW_ADDR_PLC_5        1368
#define IDC_CHECK_AXES_X                1368
#define IDC_EDIT_RROW_ADDR_PLC_6        1369
#define IDC_CHECK_AXES_X_REL            1369
#define IDC_BUTTON_OPEN_ALARM           1369
#define IDC_EDIT_RROW_ADDR_PLC_7        1370
#define IDC_CHECK_AXES_X_ZERO           1370
#define IDC_CHECKBOX_FILL_AL_AS_VAL     1370
#define IDC_COMBOBOX_PERIF_INIT_X       1371
#define IDC_EDIT_RROW_ADDR_PLC_8        1371
#define IDC_EDIT_FILL_AL_AS_VAL         1371
#define IDC_EDIT_ADDR_INIT_X            1372
#define IDC_EDIT_RROW_ADDR_PLC_9        1372
#define IDC_EDIT_FILL_AS_VAL_STEP       1372
#define IDC_COMBOBOX_TYPEVAL_INIT_X     1373
#define IDC_EDIT_RROW_ADDR_PLC_10       1373
#define IDC_EDIT_PRPH_FILTER            1373
#define IDC_BUTTON_NORMALIZ_INIT_X      1374
#define IDC_EDIT_RROW_ADDR_PLC_11       1374
#define IDC_EDIT_WZ_LKP_LINKED_PAGE     1374
#define IDC_EDIT_NORMALIZ_INIT_X        1375
#define IDC_EDIT_RROW_ADDR_PLC_12       1375
#define IDC_EDIT_WZ_LKP_LINKED_PATH     1375
#define IDC_COMBOBOX_PERIF_CURR_X       1376
#define IDC_EDIT_RROW_ADDR_PLC_13       1376
#define IDC_EDIT_WZ_LKP_TITLE           1376
#define IDC_EDIT_ADDR_CURR_X_V          1377
#define IDC_EDIT_RROW_ADDR_PLC_14       1377
#define IDC_COMBO_WZ_LKP_PRPH           1377
#define IDC_COMBOBOX_TYPEVAL_CURR_X_V   1378
#define IDC_EDIT_RROW_ADDR_PLC_15       1378
#define IDC_EDT_WZ_LKP_ADDR_PRPH        1378
#define IDC_BUTTON_NORMALIZ_CURR_X_V    1379
#define IDC_EDIT_RROW_ADDR_PLC_16       1379
#define IDC_COMBO_WZ_LKP_TYPE_PRPH      1379
#define IDC_EDIT_NORMALIZ_CURR_X        1380
#define IDC_EDIT_RROW_ADDR_PLC_17       1380
#define IDC_EDIT_WZ_LKP_BTN_PAGE        1380
#define IDC_EDIT_RROW_ADDR_PLC_18       1381
#define IDC_EDIT_WZ_LKP_PREFIX          1381
#define IDC_STATIC_PRPH_INFO            1381
#define IDC_EDIT_RROW_ADDR_PLC_19       1382
#define IDC_EDT_WZ_LKP_NUM_FILE         1382
#define IDC_EDIT_OFFSET_BIT             1382
#define IDC_EDIT_RROW_ADDR_PLC_20       1383
#define IDC_EDT_WZ_LKP_ADDR_OFFS        1383
#define IDC_RADIO_MIN_TO_MAX            1383
#define IDC_EDIT_RROW_INDICATOR         1384
#define IDC_RADIO_ZERO_TO_EDGE          1384
#define IDC_RADIO_SHOW_ZERO             1385
#define IDC_RADIO_SHOW_DASHES           1386
#define IDC_RADIO_CAM                   1387
#define IDC_RADIO_PLAYER                1388
#define IDC_RADIO_OVERWRITE             1388
#define IDC_RADIO_PREFIX                1389
#define IDC_RADIO_SUFFIX                1390
#define IDC_COMBOBOX_PERIF_MIN_Y        1390
#define IDC_CHECKBOX_ENABLE_SIMPLE_TXT  1391
#define IDC_COMBOBOX_PERIF_MAX_Y        1391
#define IDC_EDIT_SAMPLE_TEXT            1392
#define IDC_COMBOBOX_PERIF_NUM_DATA     1393
#define IDC_COMBOBOX_PERIF_ENABLE_READ  1394
#define IDC_EDIT_ADDR_PXY_MIN_Y         1395
#define IDC_COMBOBOX_TYPEVAL_PXY_MIN_Y  1396
#define IDC_BUTTON_NORMALIZ_PXY_MIN_Y   1397
#define IDC_COMBOBOX_TYPEVAL_PXY_MAX_Y  1398
#define IDC_EDIT_ADDR_PXY_MAX_Y         1399
#define IDC_BUTTON_NORMALIZ_PXY_MAX_Y   1400
#define IDC_CHECK_USE_BMP_BKG           1401
#define IDC_EDIT_NORMALIZ_PXY_MIN_Y     1401
#define IDC_CHECK_USE_BMP_BKG_ROTATE    1402
#define IDC_EDIT_NORMALIZ_PXY_MAX_Y     1402
#define IDC_CHECK_USE_BMP_BKG_MIRROR    1403
#define IDC_CHECK_AXES_Y_REL            1403
#define IDC_CHECK_USE_BMP_BAR           1404
#define IDC_STATIC_FONT_COLOR           1404
#define IDC_CHECK_USE_BMP_BAR_ROTATE    1405
#define IDC_RADIO_RCP_PASTE_APPEND      1405
#define IDC_CHECK_USE_BMP_BAR_MIRROR    1406
#define IDC_RADIO_RCP_PASTE_INSERT      1406
#define IDC_MIRROR_ALL                  1406
#define IDC_CHECK_USE_BMP_BKG_TILED     1407
#define IDC_RADIO_RCP_PASTE_OVERWRITE   1407
#define IDC_SELECTED                    1407
#define IDC_BUTTON_CLEAR_ALL            1407
#define IDC_STATICTEXT_BKG_BMP          1408
#define IDC_RADIO_RCP_PASTE_REPLACE_ALL 1408
#define IDC_RADIO_BY_FIRST_COL          1408
#define IDC_STATICTEXT_BAR_BMP          1409
#define IDC_RADIO_BY_COL2               1409
#define IDC_CHECK_USE_BMP_BAR_TILED     1410
#define IDC_EDIT_BY_ROW                 1410
#define IDC_BUTTON_NO                   1411
#define IDC_BUTTON_YES                  1412
#define IDC_TREE1                       1412
#define IDC_BUTTON_NO_ALL               1413
#define IDC_EDIT_BORDER_OFFSET_X        1413
#define IDC_BUTTON_YES_ALL              1414
#define IDC_EDIT_BORDER_OFFSET_Y        1414
#define IDC_STATIC_M_MIN_X              1414
#define IDC_STATIC_M_MIN_Y              1415
#define IDC_STATIC_M_MAX_X              1416
#define IDC_STATIC_M_MAX_Y              1417
#define IDC_STATIC_M_CURR_X             1418
#define IDC_STATIC_M_CURR_Y             1419
#define IDC_STATIC_G_MAX                1420
#define IDC_STATIC_D_MIN                1421
#define IDC_STATIC_D_MAX                1422
#define IDC_STATIC_XM_MIN               1423
#define IDC_STATIC_XM_MAX               1424
#define IDC_STATIC_XS_NBLK              1425
#define IDC_STATIC_XS_NDATA             1426
#define IDC_STATIC_XS_MIN               1427
#define IDC_STATIC_XS_MAX               1428
#define IDC_STATIC_XY_MINY              1429
#define IDC_STATIC_XY_MAXY              1430
#define IDC_STATIC_XY_MINX              1431
#define IDC_STATIC_XY_MAXX              1432
#define IDC_STATIC_XY_NDATA             1433
#define IDC_COMBO_CHOOSE_FILE_PRPH      1434
#define IDC_EDIT_CHOOSE_FILE_ADDR       1435
#define IDC_EDIT_CHOOSE_FILE_LEN        1436
#define IDC_RADIO_CHOOSE_FILE_FIX       1437
#define IDC_RADIO_CHOOSE_FILE_VAR       1438
#define IDC_CHECK_AUTO_STEP             1439
#define IDC_CHECK_AUTO_ROWS             1440
#define IDC_BUTTON1                     1440
#define IDC_BUTTON_OPEN_SOURCE          1440
#define IDC_EDIT1_CLEAR                 1441
#define IDC_EDIT1_CLEAR2                1442
#define IDC_EDIT2_CRYPT                 1442
#define IDC_CHECK_ACTIVE                1442
#define IDC_CHECK_SEND_IMMEDDIATELY     1443
#define IDC_EDIT_H_W                    1443
#define IDC_CHECK_SEND_IMMEDDIATELY2    1444
#define IDC_CHECK_CENTER_IMAGE          1444
#define IDC_CHECK_FULLIMAGE             1444
#define IDC_STATICTEXT_BMP              1445
#define IDC_CHECK_REVERSE               1447
#define IDC_CHECK_VERT                  1448
#define IDC_CHECK_READONLY              1449
#define IDC_CHECK_UPDATEALWAYS          1450
#define IDC_EDIT_ADDR_MAX               1451
#define IDC_COMBOBOX_PERIFS_MAX         1452
#define IDC_COMBOBOX_TYPEVAL_MAX        1453
#define IDC_EDIT_NBITS_MAX              1454
#define IDC_EDIT_OFFSET_MAX             1455
#define IDC_EDIT_NORMALIZ_MAX           1456
#define IDC_BUTTON_NORMALIZ_MAX         1457
#define IDC_RADIO_MOVE_VERT             1458
#define IDC_RADIO_MOVE_VERT2            1459
#define IDC_RADIO_MOVE_HORZ             1459
#define IDC_RADIOBUTTON_A_LEFT2         1463
#define IDC_RADIOBUTTON_A_RIGHT2        1464
#define IDC_RADIOBUTTON_A_CENTER2       1465
#define IDC_CHECKBOX_ENABLE_ALIGN2      1466
#define IDC_CHECK_BLINK                 2001
#define IDC_EDIT_BLINK                  2002
#define IDC_CHECKBOX_USE_FILE_SHOW      2101
#define IDC_STATICTEXT_MAX_X            2102
#define IDC_STATICTEXT_FILESHOW         2103
#define IDC_EDIT_MAX_X_SHOW             2111
#define IDC_EDIT_FILENAME_SHOW          2112
#define IDC_STATICTEXT_COLOR_LINE_SHOW  2113
#define IDC_BUTTON_LINE_SHOW            2114
#define IDC_CHECKBOX_HIDE_BALL          2115
#define IDC_CHECK_BTN_HIDE_TITLE        5102
#define IDCM_COPY                       10001
#define IDCM_PASTE                      10002
#define IDCM_UNDO                       10003
#define IDCM_FLUSH                      10004
#define IDCM_AD4                        10005
#define IDCM_ADDR_OFFSET                10006
#define IDCM_GROUP                      10007
#define IDCM_UNGROUP                    10008
#define IDCM_UNGROUP_ALL                10009
#define IDCM_COPY_CUSTOM                10010
#define IDCM_PASTE_CUSTOM               10011
#define IDC_STATICTEXT_N_ROW            11101
#define IDC_EDIT_N_ROW                  11102
#define ID_ACCELERATOR40008             40008
#define ID_ACCELERATOR40010             40010
#define IDCM_DUP                        40012
#define IDCM_LOCK                       40014
#define IDCM_HIDE                       40015
#define IDCM_PROP                       40017
#define IDCM_TOGGLE_ED_TXT              40018
#define IDCM_CENTER_VERT                40022
#define IDCM_CENTER_HORZ                40023
#define IDCM_CHECKADDR                  40025
#define IDCM_CHECKADDR_REFRESH          40027
#define IDCM_TOGGLE_CHOOSE_TXT          40029
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1459
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
